# Adiministação de Condominio

 administração de condomínios é uma tarefa que requer muita atenção e organização. Entre as diversas responsabilidades da gestão está o recebimento dos aluguéis dos locatários. Para garantir uma boa saúde financeira do empreendimento, é fundamental que esses pagamentos sejam feitos de forma regular e pontual. No entanto, sabemos que nem sempre isso acontece.

Pensando nisso, proponho um desafio de tratamento de dados com o objetivo de analisar o atraso no pagamento de aluguéis no condomínio de alguns moradores. Disponibilizo a base de dados dados_locacao_imoveis.json, que contém informações sobre o apartamento dos locatários, o dia acordado para o pagamento do aluguel, o dia da efetivação do pagamento de aluguel e o valor do aluguel.

Com essas informações, o desafio do projeto 2: administração de condomínios será similar ao desafio do projeto 1, abrir a base de dados com Pandas e aplicar o json_normalize no DataFrame.

In [2]:
import pandas as pd
import requests
import numpy as np

In [3]:

url = 'https://cdn3.gnarususercontent.com.br/2928-transformacao-manipulacao-dados/dados_locacao_imoveis.json'

# Simular um navegador
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
}

# Fazer a requisição
response = requests.get(url, headers=headers)

# Verificar se o acesso foi permitido
if response.status_code == 200:
    data = response.json()
    dados_adm_condominios = pd.DataFrame(data)
    print(dados_adm_condominios.head())
else:
    print(f"Erro {response.status_code}: Acesso negado")

                                       dados_locacao
0  {'apartamento': 'A101 (blocoAP)', 'datas_combi...
1  {'apartamento': 'A102 (blocoAP)', 'datas_combi...
2  {'apartamento': 'B201 (blocoAP)', 'datas_combi...
3  {'apartamento': 'B202 (blocoAP)', 'datas_combi...
4  {'apartamento': 'C301 (blocoAP)', 'datas_combi...

In [4]:
dados_adm_condominios = pd.json_normalize(dados_adm_condominios['dados_locacao'])
dados_adm_condominios

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"
5,C302 (blocoAP),"[06/06/2022, 06/07/2022]","[08/06/2022, 12/07/2022]","[$ 1500,0 reais, $ 1200,0 reais]"
6,D401 (blocoAP),"[07/06/2022, 07/07/2022]","[07/06/2022, 09/07/2022]","[$ 1600,0 reais, $ 1300,0 reais]"
7,D402 (blocoAP),"[08/06/2022, 08/07/2022]","[10/06/2022, 14/07/2022]","[$ 1700,0 reais, $ 1400,0 reais]"
8,E501 (blocoAP),"[09/06/2022, 09/07/2022]","[10/06/2022, 09/07/2022]","[$ 1800,0 reais, $ 1500,0 reais]"
9,E502 (blocoAP),"[10/06/2022, 10/07/2022]","[16/06/2022, 12/07/2022]","[$ 1900,0 reais, $ 1600,0 reais]"
10,F601 (blocoAP),"[11/06/2022, 11/07/2022]","[17/06/2022, 13/07/2022]","[$ 2000,0 reais, $ 1000,0 reais]"
11,F602 (blocoAP),"[12/06/2022, 12/07/2022]","[15/06/2022, 12/07/2022]","[$ 2100,0 reais, $ 1100,0 reais]"
12,G701 (blocoAP),"[13/06/2022, 13/07/2022]","[19/06/2022, 20/07/2022]","[$ 2200,0 reais, $ 1200,0 reais]"
13,G702 (blocoAP),"[14/06/2022, 14/07/2022]","[15/06/2022, 17/07/2022]","[$ 2300,0 reais, $ 2100,0 reais]"
14,H801 (blocoAP),"[15/06/2022, 15/07/2022]","[18/06/2022, 16/07/2022]","[$ 2400,0 reais, $ 2200,0 reais]"

Lemos a base de dados no desafio anterior, agora podemos avançar nas transformações desses dados. Então, da mesma forma que o projeto 1, o desafio do projeto 2 está listado em algumas metas:

- Remover os dados em listas dentro do DataFrame;
- Verificar os tipos de dados;
- Identificar colunas numéricas;
- Transformar a coluna numérica para o tipo numérico.

In [5]:
colunas = list(dados_adm_condominios.columns)
colunas

['apartamento',
 'datas_combinadas_pagamento',
 'datas_de_pagamento',
 'valor_aluguel']

In [6]:
dados_adm_condominios = dados_adm_condominios.explode(colunas[1:])
dados_adm_condominios

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
0,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
1,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
1,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
2,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"
2,B201 (blocoAP),03/07/2022,03/07/2022,"$ 2700,0 reais"
3,B202 (blocoAP),04/06/2022,07/06/2022,"$ 1300,0 reais"
3,B202 (blocoAP),04/07/2022,05/07/2022,"$ 2800,0 reais"
4,C301 (blocoAP),05/06/2022,10/06/2022,"$ 1400,0 reais"
4,C301 (blocoAP),05/07/2022,09/07/2022,"$ 2900,0 reais"
5,C302 (blocoAP),06/06/2022,08/06/2022,"$ 1500,0 reais"
5,C302 (blocoAP),06/07/2022,12/07/2022,"$ 1200,0 reais"
6,D401 (blocoAP),07/06/2022,07/06/2022,"$ 1600,0 reais"
6,D401 (blocoAP),07/07/2022,09/07/2022,"$ 1300,0 reais"
7,D402 (blocoAP),08/06/2022,10/06/2022,"$ 1700,0 reais"
7,D402 (blocoAP),08/07/2022,14/07/2022,"$ 1400,0 reais"
8,E501 (blocoAP),09/06/2022,10/06/2022,"$ 1800,0 reais"
8,E501 (blocoAP),09/07/2022,09/07/2022,"$ 1500,0 reais"
9,E502 (blocoAP),10/06/2022,16/06/2022,"$ 1900,0 reais"
9,E502 (blocoAP),10/07/2022,12/07/2022,"$ 1600,0 reais"
10,F601 (blocoAP),11/06/2022,17/06/2022,"$ 2000,0 reais"
10,F601 (blocoAP),11/07/2022,13/07/2022,"$ 1000,0 reais"
11,F602 (blocoAP),12/06/2022,15/06/2022,"$ 2100,0 reais"
11,F602 (blocoAP),12/07/2022,12/07/2022,"$ 1100,0 reais"
12,G701 (blocoAP),13/06/2022,19/06/2022,"$ 2200,0 reais"
12,G701 (blocoAP),13/07/2022,20/07/2022,"$ 1200,0 reais"
13,G702 (blocoAP),14/06/2022,15/06/2022,"$ 2300,0 reais"
13,G702 (blocoAP),14/07/2022,17/07/2022,"$ 2100,0 reais"
14,H801 (blocoAP),15/06/2022,18/06/2022,"$ 2400,0 reais"
14,H801 (blocoAP),15/07/2022,16/07/2022,"$ 2200,0 reais"

In [7]:
dados_adm_condominios.reset_index(inplace=True,drop=True)
dados_adm_condominios.head()

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
1,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
2,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
3,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
4,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"

In [8]:
dados_adm_condominios['valor_aluguel'] = dados_adm_condominios['valor_aluguel'].apply(lambda x: x.replace('$','').replace(',','.').replace('reais','').strip())
dados_adm_condominios

       apartamento datas_combinadas_pagamento datas_de_pagamento valor_aluguel
0   A101 (blocoAP)                 01/06/2022         05/06/2022        1000.0
1   A101 (blocoAP)                 01/07/2022         03/07/2022        2500.0
2   A102 (blocoAP)                 02/06/2022         02/06/2022        1100.0
3   A102 (blocoAP)                 02/07/2022         06/07/2022        2600.0
4   B201 (blocoAP)                 03/06/2022         07/06/2022        1200.0
5   B201 (blocoAP)                 03/07/2022         03/07/2022        2700.0
6   B202 (blocoAP)                 04/06/2022         07/06/2022        1300.0
7   B202 (blocoAP)                 04/07/2022         05/07/2022        2800.0
8   C301 (blocoAP)                 05/06/2022         10/06/2022        1400.0
9   C301 (blocoAP)                 05/07/2022         09/07/2022        2900.0
10  C302 (blocoAP)                 06/06/2022         08/06/2022        1500.0
11  C302 (blocoAP)                 06/07/2022         12/07/2022        1200.0
12  D401 (blocoAP)                 07/06/2022         07/06/2022        1600.0
13  D401 (blocoAP)                 07/07/2022         09/07/2022        1300.0
14  D402 (blocoAP)                 08/06/2022         10/06/2022        1700.0
15  D402 (blocoAP)                 08/07/2022         14/07/2022        1400.0
16  E501 (blocoAP)                 09/06/2022         10/06/2022        1800.0
17  E501 (blocoAP)                 09/07/2022         09/07/2022        1500.0
18  E502 (blocoAP)                 10/06/2022         16/06/2022        1900.0
19  E502 (blocoAP)                 10/07/2022         12/07/2022        1600.0
20  F601 (blocoAP)                 11/06/2022         17/06/2022        2000.0
21  F601 (blocoAP)                 11/07/2022         13/07/2022        1000.0
22  F602 (blocoAP)                 12/06/2022         15/06/2022        2100.0
23  F602 (blocoAP)                 12/07/2022         12/07/2022        1100.0
24  G701 (blocoAP)                 13/06/2022         19/06/2022        2200.0
25  G701 (blocoAP)                 13/07/2022         20/07/2022        1200.0
26  G702 (blocoAP)                 14/06/2022         15/06/2022        2300.0
27  G702 (blocoAP)                 14/07/2022         17/07/2022        2100.0
28  H801 (blocoAP)                 15/06/2022         18/06/2022        2400.0
29  H801 (blocoAP)                 15/07/2022         16/07/2022        2200.0

In [9]:
dados_adm_condominios['valor_aluguel'] = dados_adm_condominios['valor_aluguel'].astype(np.float64)

In [10]:
dados_adm_condominios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float64
dtypes: float64(1), object(3)
memory usage: 1.1+ KB

In [11]:
dados_adm_condominios['valor_aluguel'] = dados_adm_condominios['valor_aluguel'].astype(np.float64)

Buscando explicar a organização da identificação dos apartamentos, durante a criação do conjunto de dados, foi adicionado o texto (blocoAP). Esse texto informa que os nomes dos apartamentos estão organizados com a letra do bloco seguida do número do apartamento. No entanto, isso não traz nenhuma informação para nossos dados, sendo interessante realizar a remoção desse texto no conjunto de dados.

Com isso, manipule os textos na coluna apartamento para remover o texto (blocoAP) do DataFrame.

In [12]:
dados_adm_condominios['apartamento'].head()

0    A101 (blocoAP)
1    A101 (blocoAP)
2    A102 (blocoAP)
3    A102 (blocoAP)
4    B201 (blocoAP)
Name: apartamento, dtype: object

In [13]:

dados_adm_condominios['apartamento'] = dados_adm_condominios['apartamento'].str.replace('\(blocoAP\)','',regex=True)

dados_adm_condominios['apartamento'].head()

<>:1: SyntaxWarning: invalid escape sequence '\('
<>:1: SyntaxWarning: invalid escape sequence '\('
C:\Users\uilli\AppData\Local\Temp\ipykernel_4048\3652918581.py:1: SyntaxWarning: invalid escape sequence '\('
  dados_adm_condominios['apartamento'] = dados_adm_condominios['apartamento'].str.replace('\(blocoAP\)','',regex=True)

0    A101
1    A101
2    A102
3    A102
4    B201
Name: apartamento, dtype: object

Nas colunas datas_de_pagamento e datas_combinadas_pagamento, temos datas em formato 'dia/mês/ano' (dd/mm/AAAA). Transforme esses dados para o tipo datetime e busque uma forma de visualização de subconjunto que possa contribuir no objetivo do contexto que os dados estão inseridos.

In [14]:
dados_adm_condominios.head()

  apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0       A101                  01/06/2022         05/06/2022         1000.0
1       A101                  01/07/2022         03/07/2022         2500.0
2       A102                  02/06/2022         02/06/2022         1100.0
3       A102                  02/07/2022         06/07/2022         2600.0
4       B201                  03/06/2022         07/06/2022         1200.0

In [17]:
dados_adm_condominios['datas_combinadas_pagamento'] = pd.to_datetime(dados_adm_condominios['datas_combinadas_pagamento'], format='%d/%m/%Y')
dados_adm_condominios['datas_de_pagamento'] = pd.to_datetime(dados_adm_condominios['datas_de_pagamento'], format='%d/%m/%Y')

In [18]:
dados_adm_condominios.head()

  apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0       A101                  2022-06-01         2022-06-05         1000.0
1       A101                  2022-07-01         2022-07-03         2500.0
2       A102                  2022-06-02         2022-06-02         1100.0
3       A102                  2022-07-02         2022-07-06         2600.0
4       B201                  2022-06-03         2022-06-07         1200.0

A administração de condomínios é uma tarefa que requer muita atenção e organização. Entre as diversas responsabilidades da gestão está o recebimento dos aluguéis dos locatários. Para garantir uma boa saúde financeira do empreendimento, é fundamental que esses pagamentos sejam feitos de forma regular e pontual. No entanto, sabemos que nem sempre isso acontece. Pensando nisso, proponho um desafio de tratamento de dados com o objetivo de analisar o atraso no pagamento de aluguéis no condomínio fictício de alguns moradores.

In [20]:
# Para contribuir na solução do contexto é possível calcular a diferença de dias
# entre a data combinada e a data de pagamento com dt.days
dados_adm_condominios['atraso'] = (dados_adm_condominios['datas_de_pagamento'] - dados_adm_condominios['datas_combinadas_pagamento']).dt.days

In [22]:
# Calcular a média de tempo de atraso por apartamentos
media_atraso = dados_adm_condominios.groupby(['apartamento'])['atraso'].mean()

# Visualizar o resultado
media_atraso

apartamento
A101     3.0
A102     2.0
B201     2.0
B202     2.0
C301     4.5
C302     4.0
D401     1.0
D402     4.0
E501     0.5
E502     4.0
F601     4.0
F602     1.5
G701     6.5
G702     2.0
H801     2.0
Name: atraso, dtype: float64