# Precificação Inteligente

A precificação inteligente para hospedagem é uma estratégia de estimação de preços de forma automatizada e dinâmica, que considera fatores como oferta e demanda, sazonalidade, eventos locais, características do local, entre outros. Com base nessas informações, um algoritmo pode ajustar os preços para maximizar a receita e a rentabilidade da pessoa proprietária.

Normalmente essa estratégia é aplicada a um modelo de inteligência artificial que ajusta automaticamente os preços das diárias. Por exemplo, se a demanda por hospedagem em um determinado destino aumentar, a precificação inteligente ajustará automaticamente os preços das diárias para cima, com o fim de maximizar a receita da propriedade. Da mesma forma, se a demanda diminuir, a precificação inteligente ajustará os preços para baixo para manter a ocupação da propriedade e evitar perdas financeiras.

Embora o machine learning seja frequentemente usado em sistemas de precificação inteligente, existem outras abordagens que podem ser usadas para implementar esses sistemas. Por exemplo, pode-se usar um modelo de regras baseado em lógica e heurísticas para definir as condições e regras de precificação.

Mesmo assim, é importante ressaltar que o uso de machine learning pode oferecer benefícios adicionais, como a capacidade de analisar grandes volumes de dados, identificar padrões de comportamento do consumidor e ajustar os preços de forma mais precisa e dinâmica.

In [ ]:
import pandas as pd
import requests
import numpy as np

In [3]:

url = 'https://cdn3.gnarususercontent.com.br/2928-transformacao-manipulacao-dados/moveis_disponiveis.json'

# Simular um navegador
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
}

# Fazer a requisição
response = requests.get(url, headers=headers)

# Verificar se o acesso foi permitido
if response.status_code == 200:
    data = response.json()
    moveis_disponiveis = pd.DataFrame(data)
    print(moveis_disponiveis.head())
else:
    print(f"Erro {response.status_code}: Acesso negado")

    id        data  vaga_disponivel preco
0  857  2016-01-04            False  None
1  857  2016-01-05            False  None
2  857  2016-01-06            False  None
3  857  2016-01-07            False  None
4  857  2016-01-08            False  None

In [4]:
url = 'https://cdn3.gnarususercontent.com.br/2928-transformacao-manipulacao-dados/dados_hospedagem.json'

# Simular um navegador
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
}

# Fazer a requisição
response = requests.get(url, headers=headers)

# Verificar se o acesso foi permitido
if response.status_code == 200:
    data = response.json()
    dados_hospedagem = pd.DataFrame(data)
    print(dados_hospedagem.head())
else:
    print(f"Erro {response.status_code}: Acesso negado")

                                         info_moveis
0  {'avaliacao_geral': '10.0', 'experiencia_local...
1  {'avaliacao_geral': '10.0', 'experiencia_local...
2  {'avaliacao_geral': '10.0', 'experiencia_local...
3  {'avaliacao_geral': '10.0', 'experiencia_local...
4  {'avaliacao_geral': '10.0', 'experiencia_local...

### Normalização

In [5]:
dados_hospedagem = pd.json_normalize(dados_hospedagem['info_moveis'])
dados_hospedagem

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,[This clean and comfortable one bedroom sits r...,[Lower Queen Anne is near the Seattle Center (...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[Real Bed, Futon, Futon, Pull-out Sofa, Real B...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...","[$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...","[$110.00, $45.00, $55.00, $52.00, $85.00, $50...."
1,10.0,--,10,[Welcome to the heart of the 'Ballard Brewery ...,"[--, Capital Hill is the heart of Seattle, bor...","[2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]","[3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]","[5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$500.00, $300.00, $0, $300.00, $300.00, $360....","[$125.00, $100.00, $85.00, $110.00, $110.00, $...","[$350.00, $300.00, $425.00, $300.00, $285.00, ..."
2,10.0,--,11,[New modern house built in 2013. Spectacular ...,[Upper Queen Anne is a charming neighborhood f...,[4],[5],[7],[Real Bed],"[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00]",[$300.00],[$975.00]
3,10.0,--,12,[Our NW style home is 3200+ sq ft with 3 level...,[The Views from our top floor! Wallingford ha...,"[3, 3, 3, 3, 3, 3, 3, 3]","[6, 6, 5, 5, 5, 5, 4, 4]","[6, 6, 7, 8, 7, 7, 6, 6]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$500.00, $500.00, $500.00, $500.00, $500.00, ...","[$225.00, $300.00, $250.00, $250.00, $250.00, ...","[$490.00, $550.00, $350.00, $350.00, $350.00, ..."
4,10.0,--,14,"[Perfect for groups. 2 bedrooms, full bathroom...",[Safeway grocery store within walking distance...,"[2, 3]","[2, 6]","[3, 9]","[Real Bed, Real Bed]","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$300.00, $2,000.00]","[$40.00, $150.00]","[$200.00, $545.00]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,nan,--,5,[Our cozy little bungalow is the perfect place...,[The Queen Anne neighborhood is one of the mos...,"[1, 3, 2, 2, 2, 1, 2, 1, 1, 1, 2, 3, 2, 2, 2, ...","[2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, ...","[3, 2, 2, 3, 3, 2, 3, 2, 2, 3, 3, 3, 2, 3, 2, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{""Cable TV"",""Wireless Internet"",Kitchen,""Free...","[$250.00, $200.00, $0, $0, $0, $200.00, $350.0...","[$35.00, $50.00, $100.00, $100.00, $0, $30.00,...","[$150.00, $200.00, $143.00, $150.00, $350.00, ..."
66,nan,--,6,[Bright clean 2 bedroom 1 bath appartment in t...,[Ballard is the most interesting and ecclectic...,"[1, 1, 3, 2, 1, 3, 2, 2, 1, 2, 2, 2, 1, 2, 1, ...","[2, 3, 3, 2, 2, 3, 2, 3, 2, 2, 2, 2, 4, 3, 3, ...","[3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 2, 2, 4, 4, 3, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,""Cable TV"",Internet,""Wireless Internet"",K...","[$200.00, $200.00, $100.00, $0, $0, $750.00, $...","[$0, $0, $100.00, $0, $75.00, $140.00, $112.00...","[$99.00, $185.00, $250.00, $200.00, $275.00, $..."
67,nan,--,7,[Beautiful end-unit townhome with lots of dayl...,"[Cherry blossoms (Sakura) in the spring, every...","[4, 3, 1, 2, 2, 1, 2, 1, 2, 2]","[3, 4, 3, 3, 3, 3, 3, 3, 3, 4]","[3, 5, 1, 5, 3, 2, 3, 4, 4, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$750.00, $350.00, $500.00, $500.00, $0, $200....","[$300.00, $90.00, $250.00, $100.00, $109.00, $...","[$218.00, $350.00, $450.00, $149.00, $99.00, $..."
68,nan,--,8,[Heart of Ballard new townhome with 4 BRs + ba...,"[--, --, The suite is conveniently located off...","[2, 2, 3, 1, 1, 2, 1, 3, 2, 1, 2, 1, 2, 2, 2, ...","[4, 2, 3, 4, 3, 3, 4, 4, 3, 5, 2, 3, 3, 4, 5, ...","[4, 4, 3, 3, 5, 5, 5, 5, 3, 5, 4, 5, 5, 4, 1, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",""Air Conditi...","[$500.00, $150.00, $250.00, $800.00, $0, $500....","[$50.00, $85.00, $150.00, $75.00, $100.00, $80...","[$275.00, $199.00, $400.00, $325.00, $300.00, ..."
69,nan,--,9,[This business-themed modern home features: *...,[Your hosts made Madison Valley their home whe...,"[2, 1]","[3, 4]","[6, 6]","[Real Bed, Real Bed]","[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00, $500.00]","[$150.00, $0]","[$250.00, $350.00]"

- avaliacao_geral: refere-se à média de notas dadas para a avaliação da hospedagem no imóvel.
- experiencia_local: descreve as experiências oferecidas durante a hospedagem no imóvel.
- max_hospedes: informa a quantidade máxima de hóspedes que o local permite.
- descricao_local: descreve o imóvel.
- descricao_vizinhanca: descreve a vizinhança ao redor do imóvel.
- quantidade_banheiros: informa a quantidade de banheiros disponíveis.
- quantidade_quartos: informa a quantidade de quartos disponíveis.
- quantidade_camas: informa a quantidade de camas disponíveis.
- modelo_cama: informa o modelo de cama oferecido.
- comodidades: informa as comodidades oferecidas pelo imóvel.
- taxa_deposito: informa a taxa de depósito mínima para segurança de hospedagem.
- taxa_limpeza: informa a taxa cobrada para o serviço de limpeza.
- preco: refere-se ao preço base a ser cobrado pela diária no imóvel.

In [6]:
colunas = list(dados_hospedagem.columns)
colunas

['avaliacao_geral',
 'experiencia_local',
 'max_hospedes',
 'descricao_local',
 'descricao_vizinhanca',
 'quantidade_banheiros',
 'quantidade_quartos',
 'quantidade_camas',
 'modelo_cama',
 'comodidades',
 'taxa_deposito',
 'taxa_limpeza',
 'preco']

In [7]:
dados_hospedagem = dados_hospedagem.explode(colunas[3:])
dados_hospedagem

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
0,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
0,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
0,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
0,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,nan,--,8,Beautiful craftsman home in the historic Wedgw...,--,3,4,5,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$178.00,$299.00
68,nan,--,8,Located in a very easily accessible area of Se...,"Quiet, dead end street near I-5. The proximity...",2,4,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",$0,$99.00,$199.00
68,nan,--,8,This home is fully furnished and available wee...,--,1,3,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",$0,$0,$400.00
69,nan,--,9,This business-themed modern home features: *H...,Your hosts made Madison Valley their home when...,2,3,6,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$150.00,$250.00
69,nan,--,9,This welcoming home is in the quiet residentia...,"Despite the quiet, leafy streets of this resid...",1,4,6,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$500.00,$0,$350.00

In [8]:
dados_hospedagem.reset_index(inplace=True,drop=True)
dados_hospedagem.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00

In [9]:
dados_hospedagem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   object
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   object
 6   quantidade_quartos    3818 non-null   object
 7   quantidade_camas      3818 non-null   object
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: object(13)
memory usage: 387.9+ KB

In [10]:
dados_hospedagem['max_hospedes'] = dados_hospedagem['max_hospedes'].astype(np.int64)

In [11]:
dados_hospedagem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   object
 6   quantidade_quartos    3818 non-null   object
 7   quantidade_camas      3818 non-null   object
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: int64(1), object(12)
memory usage: 387.9+ KB

In [12]:
col_numericas = ['quantidade_banheiros','quantidade_quartos','quantidade_camas']

In [13]:
dados_hospedagem[col_numericas] = dados_hospedagem[col_numericas].astype(np.int64)

In [14]:
dados_hospedagem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: int64(4), object(9)
memory usage: 387.9+ KB

In [15]:
dados_hospedagem['avaliacao_geral'] = dados_hospedagem['avaliacao_geral'].astype(np.float64)

In [16]:
dados_hospedagem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: float64(1), int64(4), object(8)
memory usage: 387.9+ KB

In [17]:
dados_hospedagem['preco'] = dados_hospedagem['preco'].apply(lambda x: x.replace('$','').replace(',','').strip())

In [18]:
dados_hospedagem['preco'] = dados_hospedagem['preco'].astype(np.float64)

In [19]:
dados_hospedagem[['taxa_deposito','taxa_limpeza']] = dados_hospedagem[['taxa_deposito','taxa_limpeza']].applymap(lambda x: x.replace('$','').replace(',','').strip())

C:\Users\uilli\AppData\Local\Temp\ipykernel_6220\4119622283.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  dados_hospedagem[['taxa_deposito','taxa_limpeza']] = dados_hospedagem[['taxa_deposito','taxa_limpeza']].applymap(lambda x: x.replace('$','').replace(',','').strip())

In [20]:
dados_hospedagem[['taxa_deposito','taxa_limpeza']] = dados_hospedagem[['taxa_deposito','taxa_limpeza']].astype(np.float64)

In [21]:
dados_hospedagem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   float64
 11  taxa_limpeza          3818 non-null   float64
 12  preco                 3818 non-null   float64
dtypes: float64(4), int64(4), object(5)
memory usage: 387.9+ KB

In [22]:
dados_hospedagem['descricao_local'] = dados_hospedagem['descricao_local'].str.lower()

In [23]:
dados_hospedagem['descricao_local'][3025]

"one block from pike place market, the best of seattle's downtown is at your fingertips in the beautiful harbor steps apartments. this unit features 2 bedroom, 2 bathroom, is family friendly and handicap accessible, and sleeps 6. unit has been renovated! updated pics coming soon! 2 blocks to pike place market and 1/2 block to water and piers!!! live like a local during your stay at the amazing harbor steps property located in the heart of downtown seattle! you'll be a couple blocks away from the famous pike place market and right in the middle of all the action. experience everything that seattle has to offer: fantastic dining, vibrant nightlife, and exciting family activities! the harbor steps property is located on first avenue, between seneca and university in the belltown neighborhood, two blocks from seattle waterfront. the property is an easy trip from sea-tac airport by car and rail. harbor steps: -2 bedrooms with a king bed and a queen bed, and either a pull-out sofa or 2 rollaw"

In [24]:
dados_hospedagem['descricao_local'] = dados_hospedagem['descricao_local'].str.replace('[^a-zA-Z0-9\-\']',' ',regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\-'
<>:1: SyntaxWarning: invalid escape sequence '\-'
C:\Users\uilli\AppData\Local\Temp\ipykernel_6220\496006884.py:1: SyntaxWarning: invalid escape sequence '\-'
  dados_hospedagem['descricao_local'] = dados_hospedagem['descricao_local'].str.replace('[^a-zA-Z0-9\-\']',' ',regex=True)

In [25]:
dados_hospedagem['descricao_local'] = dados_hospedagem['descricao_local'].str.replace('(?<!\w)-(?!\w)',' ',regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
C:\Users\uilli\AppData\Local\Temp\ipykernel_6220\360550108.py:1: SyntaxWarning: invalid escape sequence '\w'
  dados_hospedagem['descricao_local'] = dados_hospedagem['descricao_local'].str.replace('(?<!\w)-(?!\w)',' ',regex=True)

In [26]:
dados_hospedagem['descricao_local'] = dados_hospedagem['descricao_local'].str.split()
dados_hospedagem.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,"[this, clean, and, comfortable, one, bedroom, ...",Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,0.0,110.0
1,10.0,--,1,"[our, century, old, upper, queen, anne, house,...","Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,45.0
2,10.0,--,1,"[cozy, room, in, two-bedroom, apartment, along...",The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,55.0
3,10.0,--,1,"[very, lovely, and, cozy, room, for, one, conv...","Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,20.0,52.0
4,10.0,--,1,"[the, studio, at, mibbett, hollow', is, in, a,...",--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",0.0,15.0,85.0

In [27]:
dados_hospedagem['comodidades'] = dados_hospedagem['comodidades'].str.replace('\{|}|\"','',regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\{'
<>:1: SyntaxWarning: invalid escape sequence '\{'
C:\Users\uilli\AppData\Local\Temp\ipykernel_6220\3820530292.py:1: SyntaxWarning: invalid escape sequence '\{'
  dados_hospedagem['comodidades'] = dados_hospedagem['comodidades'].str.replace('\{|}|\"','',regex=True)

In [28]:
dados_hospedagem['comodidades']

0       Internet,Wireless Internet,Kitchen,Free Parkin...
1       TV,Internet,Wireless Internet,Kitchen,Free Par...
2       TV,Internet,Wireless Internet,Kitchen,Free Par...
3       Internet,Wireless Internet,Kitchen,Free Parkin...
4       Wireless Internet,Kitchen,Free Parking on Prem...
                              ...
3813    TV,Cable TV,Internet,Wireless Internet,Air Con...
3814    TV,Cable TV,Internet,Wireless Internet,Kitchen...
3815    TV,Cable TV,Internet,Wireless Internet,Air Con...
3816    TV,Cable TV,Internet,Wireless Internet,Air Con...
3817    TV,Internet,Wireless Internet,Kitchen,Free Par...
Name: comodidades, Length: 3818, dtype: object

In [29]:
dados_hospedagem['comodidades'] = dados_hospedagem['comodidades'].str.lower()
dados_hospedagem['comodidades'] = dados_hospedagem['comodidades'].str.split(',')
dados_hospedagem['comodidades']

0       [internet, wireless internet, kitchen, free pa...
1       [tv, internet, wireless internet, kitchen, fre...
2       [tv, internet, wireless internet, kitchen, fre...
3       [internet, wireless internet, kitchen, free pa...
4       [wireless internet, kitchen, free parking on p...
                              ...
3813    [tv, cable tv, internet, wireless internet, ai...
3814    [tv, cable tv, internet, wireless internet, ki...
3815    [tv, cable tv, internet, wireless internet, ai...
3816    [tv, cable tv, internet, wireless internet, ai...
3817    [tv, internet, wireless internet, kitchen, fre...
Name: comodidades, Length: 3818, dtype: object

In [30]:
#deixando minuscula
dados_hospedagem['descricao_vizinhanca'] = dados_hospedagem['descricao_vizinhanca'].str.lower()
#remove caractere especial
dados_hospedagem['descricao_vizinhanca'] = dados_hospedagem['descricao_vizinhanca'].str.replace('[^a-zA-Z0-9\-\']',' ',regex=True)
#remove ifem em palavras compostas 
dados_hospedagem['descricao_vizinhanca'] = dados_hospedagem['descricao_vizinhanca'].str.replace('(?<!\w)-(?!\w)',' ',regex=True)
#fazendo tokanização 
dados_hospedagem['descricao_vizinhanca'] = dados_hospedagem['descricao_vizinhanca'].str.split()
dados_hospedagem.head()

<>:4: SyntaxWarning: invalid escape sequence '\-'
<>:6: SyntaxWarning: invalid escape sequence '\w'
<>:4: SyntaxWarning: invalid escape sequence '\-'
<>:6: SyntaxWarning: invalid escape sequence '\w'
C:\Users\uilli\AppData\Local\Temp\ipykernel_6220\2022237372.py:4: SyntaxWarning: invalid escape sequence '\-'
  dados_hospedagem['descricao_vizinhanca'] = dados_hospedagem['descricao_vizinhanca'].str.replace('[^a-zA-Z0-9\-\']',' ',regex=True)
C:\Users\uilli\AppData\Local\Temp\ipykernel_6220\2022237372.py:6: SyntaxWarning: invalid escape sequence '\w'
  dados_hospedagem['descricao_vizinhanca'] = dados_hospedagem['descricao_vizinhanca'].str.replace('(?<!\w)-(?!\w)',' ',regex=True)

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,"[this, clean, and, comfortable, one, bedroom, ...","[lower, queen, anne, is, near, the, seattle, c...",1,1,1,Real Bed,"[internet, wireless internet, kitchen, free pa...",0.0,0.0,110.0
1,10.0,--,1,"[our, century, old, upper, queen, anne, house,...","[upper, queen, anne, is, a, really, pleasant, ...",1,1,1,Futon,"[tv, internet, wireless internet, kitchen, fre...",0.0,0.0,45.0
2,10.0,--,1,"[cozy, room, in, two-bedroom, apartment, along...","[the, convenience, of, being, in, seattle, but...",1,1,1,Futon,"[tv, internet, wireless internet, kitchen, fre...",0.0,0.0,55.0
3,10.0,--,1,"[very, lovely, and, cozy, room, for, one, conv...","[ballard, is, lovely, vibrant, and, one, of, t...",1,1,1,Pull-out Sofa,"[internet, wireless internet, kitchen, free pa...",0.0,20.0,52.0
4,10.0,--,1,"[the, studio, at, mibbett, hollow', is, in, a,...",[],1,1,1,Real Bed,"[wireless internet, kitchen, free parking on p...",0.0,15.0,85.0

In [31]:
moveis_disponiveis.head()

    id        data  vaga_disponivel preco
0  857  2016-01-04            False  None
1  857  2016-01-05            False  None
2  857  2016-01-06            False  None
3  857  2016-01-07            False  None
4  857  2016-01-08            False  None

In [32]:
moveis_disponiveis.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  object
 2   vaga_disponivel  365000 non-null  bool
 3   preco            270547 non-null  object
dtypes: bool(1), int64(1), object(2)
memory usage: 11.5+ MB

In [34]:
moveis_disponiveis['data'] = pd.to_datetime(moveis_disponiveis['data'])

In [35]:
moveis_disponiveis.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  datetime64[ns]
 2   vaga_disponivel  365000 non-null  bool
 3   preco            270547 non-null  object
dtypes: bool(1), datetime64[ns](1), int64(1), object(1)
memory usage: 19.5+ MB

In [36]:
moveis_disponiveis['data'].dt.strftime('%Y-%m')

0         2016-01
1         2016-01
2         2016-01
3         2016-01
4         2016-01
           ...
364995    2016-12
364996    2016-12
364997    2016-12
364998    2017-01
364999    2017-01
Name: data, Length: 365000, dtype: object

In [39]:
sub_set = moveis_disponiveis.groupby(moveis_disponiveis['data'].dt.strftime('%Y-%m'))['vaga_disponivel'].sum()
sub_set

data
2016-01    16543
2016-02    20128
2016-03    23357
2016-04    22597
2016-05    23842
2016-06    23651
2016-07    22329
2016-08    22529
2016-09    22471
2016-10    23765
2016-11    23352
2016-12    24409
2017-01     1574
Name: vaga_disponivel, dtype: int64

In [41]:
moveis_disponiveis['preco']

0            None
1            None
2            None
3            None
4            None
           ...
364995    $140.00
364996    $140.00
364997    $140.00
364998    $140.00
364999       None
Name: preco, Length: 365000, dtype: object

In [44]:
# utilizamos o método fillna para preencher os elementos vazios por '0.0'
# definimos o parâmetro de inplace para True para substituir no DataFrame
moveis_disponiveis['preco'].fillna('0.0', inplace = True)

# apagamos o $ e as vírgulas com apply lambda
moveis_disponiveis['preco'] = moveis_disponiveis['preco'].apply(lambda x: x.replace('$', '').replace(',',''))

# transformamos os tipos de dados para float64
moveis_disponiveis['preco'] = moveis_disponiveis['preco'].astype(np.float64)

# observamos o resultado final
moveis_disponiveis

          id       data  vaga_disponivel  preco
0        857 2016-01-04            False    0.0
1        857 2016-01-05            False    0.0
2        857 2016-01-06            False    0.0
3        857 2016-01-07            False    0.0
4        857 2016-01-08            False    0.0
...      ...        ...              ...    ...
364995  3279 2016-12-29             True  140.0
364996  3279 2016-12-30             True  140.0
364997  3279 2016-12-31             True  140.0
364998  3279 2017-01-01             True  140.0
364999  3279 2017-01-02            False    0.0

[365000 rows x 4 columns]