Conectando a Base de dados

In [0]:
dbutils.fs.ls("dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/data/")

Out[107]: [FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/data/data.csv', name='data.csv', size=29654587, modificationTime=1735929469000),
 FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/data/data_by_artist.csv', name='data_by_artist.csv', size=4315607, modificationTime=1735929454000),
 FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/data/data_by_genres.csv', name='data_by_genres.csv', size=576456, modificationTime=1735929456000),
 FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/data/data_by_year.csv', name='data_by_year.csv', size=21194, modificationTime=1735929457000),
 FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/data/data_w_genres.csv', name='data_w_genres.csv', size=5224673, modificationTime=1735929461000)]

In [0]:
path_data = 'dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/data/data.csv'

In [0]:
df_data =  spark.read.csv(path_data,inferSchema=True,header=True)

In [0]:
df_data.show(5)

+-------+----+------------+--------------------+------------------+-----------+------+--------+--------------------+----------------+---+--------+--------+----+--------------------+----------+------------+-----------+-----------------+
|valence|year|acousticness|             artists|      danceability|duration_ms|energy|explicit|                  id|instrumentalness|key|liveness|loudness|mode|                name|popularity|release_date|speechiness|            tempo|
+-------+----+------------+--------------------+------------------+-----------+------+--------+--------------------+----------------+---+--------+--------+----+--------------------+----------+------------+-----------+-----------------+
| 0.0594|1921|       0.982|['Sergei Rachmani...|             0.279|     831667| 0.211|       0|4BJqT0PrAfrxzMOxy...|           0.878| 10|   0.665| -20.096|   1|Piano Concerto No...|         4|        1921|     0.0366|           80.954|
|  0.963|1921|       0.732|      ['Dennis Day']|0.8190000000000001|     180533| 0.341|       0|7xPhfUan2yNtyFG0c...|             0.0|  7|    0.16| -12.441|   1|Clancy Lowered th...|         5|        1921|      0.415|60.93600000000001|
| 0.0394|1921|       0.961|['KHP Kridhamarda...|             0.328|     500062| 0.166|       0|1o6I8BglA6ylDMrIE...|           0.913|  3|   0.101|  -14.85|   1|           Gati Bali|         5|        1921|     0.0339|          110.339|
|  0.165|1921|       0.967|    ['Frank Parker']|             0.275|     210000| 0.309|       0|3ftBPsC5vPBKxYSee...|        2.77e-05|  5|   0.381|  -9.316|   1|           Danny Boy|         3|        1921|     0.0354|          100.109|
|  0.253|1921|       0.957|      ['Phil Regan']|             0.418|     166693| 0.193|       0|4d6HGyGT8e121BsdK...|        1.68e-06|  3|   0.229| -10.096|   1|When Irish Eyes A...|         2|        1921|      0.038|          101.665|
+-------+----+------------+--------------------+------------------+-----------+------+--------+--------------------+----------------+---+--------+--------+----+--------------------+----------+------------+-----------+-----------------+
only showing top 5 rows

In [0]:
type(df_data)

Out[111]: pyspark.sql.dataframe.DataFrame

In [0]:
df_data = df_data.pandas_api()

In [0]:
type(df_data)

Out[113]: pyspark.pandas.frame.DataFrame

In [0]:
df_data.head()

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
0,0.0594,1921,0.982,"['Sergei Rachmaninoff', 'James Levine', 'Berli...",0.279,831667,0.211,0,4BJqT0PrAfrxzMOxytFOIz,0.878,10,0.665,-20.096,1,"Piano Concerto No. 3 in D Minor, Op. 30: III. ...",4,1921,0.0366,80.954
1,0.9630,1921,0.732,['Dennis Day'],0.8190000000000001,180533,0.341,0,7xPhfUan2yNtyFG0cUWkt8,0.0,7,0.16,-12.441,1,Clancy Lowered the Boom,5,1921,0.415,60.93600000000001
2,0.0394,1921,0.961,['KHP Kridhamardawa Karaton Ngayogyakarta Hadi...,0.328,500062,0.166,0,1o6I8BglA6ylDMrIELygv1,0.913,3,0.101,-14.85,1,Gati Bali,5,1921,0.0339,110.339
3,0.1650,1921,0.967,['Frank Parker'],0.275,210000,0.309,0,3ftBPsC5vPBKxYSee08FDH,2.77e-05,5,0.381,-9.316,1,Danny Boy,3,1921,0.0354,100.109
4,0.2530,1921,0.957,['Phil Regan'],0.418,166693,0.193,0,4d6HGyGT8e121BsdKmw9v6,1.68e-06,3,0.229,-10.096,1,When Irish Eyes Are Smiling,2,1921,0.038,101.665

In [0]:
df_data.info()

<class 'pyspark.pandas.frame.DataFrame'>
Int64Index: 170653 entries, 0 to 170652
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   valence           170653 non-null  float64
 1   year              170653 non-null  int32
 2   acousticness      170653 non-null  float64
 3   artists           170653 non-null  object
 4   danceability      170653 non-null  object
 5   duration_ms       170653 non-null  object
 6   energy            170653 non-null  object
 7   explicit          170653 non-null  object
 8   id                170653 non-null  object
 9   instrumentalness  170653 non-null  object
 10  key               170653 non-null  object
 11  liveness          170653 non-null  object
 12  loudness          170653 non-null  object
 13  mode              170653 non-null  object
 14  name              170653 non-null  object
 15  popularity        170653 non-null  object
 16  release_date      170653 non-null  object
 17  speechiness       170653 non-null  object
 18  tempo             170653 non-null  object
dtypes: float64(2), int32(1), object(16)

In [0]:
columns_float = ['acousticness','danceability','energy','instrumentalness','liveness','loudness','speechiness','tempo','valence']
columns_int = ['duration_ms','mode','key','explicit','popularity']

In [0]:
df_data[columns_float] =  df_data[columns_float].astype(float)
df_data[columns_int] =  df_data[columns_int].astype(int)

In [0]:
df_data.info()

<class 'pyspark.pandas.frame.DataFrame'>
Int64Index: 170653 entries, 0 to 170652
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   valence           170653 non-null  float64
 1   year              170653 non-null  int32
 2   acousticness      170653 non-null  float64
 3   artists           170653 non-null  object
 4   danceability      170080 non-null  float64
 5   duration_ms       170454 non-null  int64
 6   energy            170573 non-null  float64
 7   explicit          170606 non-null  int64
 8   id                170653 non-null  object
 9   instrumentalness  170270 non-null  float64
 10  key               170451 non-null  int64
 11  liveness          170613 non-null  float64
 12  loudness          170621 non-null  float64
 13  mode              170635 non-null  int64
 14  name              170653 non-null  object
 15  popularity        169496 non-null  int64
 16  release_date      170653 non-null  object
 17  speechiness       170042 non-null  float64
 18  tempo             170404 non-null  float64
dtypes: float64(9), int32(1), int64(5), object(4)

Ajustando a coluna "Artistas"

In [0]:
type(df_data.artists.iloc[0])

Out[119]: str

In [0]:
X = df_data.iloc[0:9]
X

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
0,0.0594,1921,0.982,"['Sergei Rachmaninoff', 'James Levine', 'Berli...",0.279,831667,0.211,0,4BJqT0PrAfrxzMOxytFOIz,0.878000,10,0.665,-20.096,1,"Piano Concerto No. 3 in D Minor, Op. 30: III. ...",4,1921,0.0366,80.954
1,0.9630,1921,0.732,['Dennis Day'],0.819,180533,0.341,0,7xPhfUan2yNtyFG0cUWkt8,0.000000,7,0.160,-12.441,1,Clancy Lowered the Boom,5,1921,0.4150,60.936
2,0.0394,1921,0.961,['KHP Kridhamardawa Karaton Ngayogyakarta Hadi...,0.328,500062,0.166,0,1o6I8BglA6ylDMrIELygv1,0.913000,3,0.101,-14.850,1,Gati Bali,5,1921,0.0339,110.339
3,0.1650,1921,0.967,['Frank Parker'],0.275,210000,0.309,0,3ftBPsC5vPBKxYSee08FDH,0.000028,5,0.381,-9.316,1,Danny Boy,3,1921,0.0354,100.109
4,0.2530,1921,0.957,['Phil Regan'],0.418,166693,0.193,0,4d6HGyGT8e121BsdKmw9v6,0.000002,3,0.229,-10.096,1,When Irish Eyes Are Smiling,2,1921,0.0380,101.665
5,0.1960,1921,0.579,['KHP Kridhamardawa Karaton Ngayogyakarta Hadi...,0.697,395076,0.346,0,4pyw9DVHGStUre4J6hPngr,0.168000,2,0.130,-12.506,1,Gati Mardika,6,1921,0.0700,119.824
6,0.4060,1921,0.996,['John McCormack'],0.518,159507,0.203,0,5uNZnElqOS3W4fRmRYPk4T,0.000000,0,0.115,-10.589,1,The Wearing of the Green,4,1921,0.0615,66.221
7,0.0731,1921,0.993,['Sergei Rachmaninoff'],0.389,218773,0.088,0,02GDntOXexBFUvSgaXLPkd,0.527000,1,0.363,-21.091,0,"Morceaux de fantaisie, Op. 3: No. 2, Prélude i...",2,1921,0.0456,92.867
8,0.7210,1921,0.996,['Ignacio Corsini'],0.485,161520,0.130,0,05xDjWH9ub67nJJk82yfGf,0.151000,5,0.104,-21.508,0,La Mañanita - Remasterizado,0,1921-03-20,0.0483,64.678

In [0]:
X['artists'] = X.artists.str.replace("\[|\]|\'","")
X['artists'] = X.artists.str.replace(",",";")

In [0]:
X

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
0,0.0594,1921,0.982,Sergei Rachmaninoff; James Levine; Berliner Ph...,0.279,831667,0.211,0,4BJqT0PrAfrxzMOxytFOIz,0.878000,10,0.665,-20.096,1,"Piano Concerto No. 3 in D Minor, Op. 30: III. ...",4,1921,0.0366,80.954
1,0.9630,1921,0.732,Dennis Day,0.819,180533,0.341,0,7xPhfUan2yNtyFG0cUWkt8,0.000000,7,0.160,-12.441,1,Clancy Lowered the Boom,5,1921,0.4150,60.936
2,0.0394,1921,0.961,KHP Kridhamardawa Karaton Ngayogyakarta Hadini...,0.328,500062,0.166,0,1o6I8BglA6ylDMrIELygv1,0.913000,3,0.101,-14.850,1,Gati Bali,5,1921,0.0339,110.339
3,0.1650,1921,0.967,Frank Parker,0.275,210000,0.309,0,3ftBPsC5vPBKxYSee08FDH,0.000028,5,0.381,-9.316,1,Danny Boy,3,1921,0.0354,100.109
4,0.2530,1921,0.957,Phil Regan,0.418,166693,0.193,0,4d6HGyGT8e121BsdKmw9v6,0.000002,3,0.229,-10.096,1,When Irish Eyes Are Smiling,2,1921,0.0380,101.665
5,0.1960,1921,0.579,KHP Kridhamardawa Karaton Ngayogyakarta Hadini...,0.697,395076,0.346,0,4pyw9DVHGStUre4J6hPngr,0.168000,2,0.130,-12.506,1,Gati Mardika,6,1921,0.0700,119.824
6,0.4060,1921,0.996,John McCormack,0.518,159507,0.203,0,5uNZnElqOS3W4fRmRYPk4T,0.000000,0,0.115,-10.589,1,The Wearing of the Green,4,1921,0.0615,66.221
7,0.0731,1921,0.993,Sergei Rachmaninoff,0.389,218773,0.088,0,02GDntOXexBFUvSgaXLPkd,0.527000,1,0.363,-21.091,0,"Morceaux de fantaisie, Op. 3: No. 2, Prélude i...",2,1921,0.0456,92.867
8,0.7210,1921,0.996,Ignacio Corsini,0.485,161520,0.130,0,05xDjWH9ub67nJJk82yfGf,0.151000,5,0.104,-21.508,0,La Mañanita - Remasterizado,0,1921-03-20,0.0483,64.678

In [0]:
df_data['artists'] = df_data.artists.str.replace("\[|\]|\'","")
df_data['artists'] = df_data.artists.str.replace(",",";")
df_data.head()

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
0,0.0594,1921,0.982,Sergei Rachmaninoff; James Levine; Berliner Ph...,0.279,831667,0.211,0,4BJqT0PrAfrxzMOxytFOIz,0.878000,10,0.665,-20.096,1,"Piano Concerto No. 3 in D Minor, Op. 30: III. ...",4,1921,0.0366,80.954
1,0.9630,1921,0.732,Dennis Day,0.819,180533,0.341,0,7xPhfUan2yNtyFG0cUWkt8,0.000000,7,0.160,-12.441,1,Clancy Lowered the Boom,5,1921,0.4150,60.936
2,0.0394,1921,0.961,KHP Kridhamardawa Karaton Ngayogyakarta Hadini...,0.328,500062,0.166,0,1o6I8BglA6ylDMrIELygv1,0.913000,3,0.101,-14.850,1,Gati Bali,5,1921,0.0339,110.339
3,0.1650,1921,0.967,Frank Parker,0.275,210000,0.309,0,3ftBPsC5vPBKxYSee08FDH,0.000028,5,0.381,-9.316,1,Danny Boy,3,1921,0.0354,100.109
4,0.2530,1921,0.957,Phil Regan,0.418,166693,0.193,0,4d6HGyGT8e121BsdKmw9v6,0.000002,3,0.229,-10.096,1,When Irish Eyes Are Smiling,2,1921,0.0380,101.665

In [0]:
# Carregando o arquivo data_by_year.csv utilizando o Spark
df_data_year = spark.read.format('csv') \
.option("inferSchema", 'True') \
.option("header", 'True') \
.option("sep", ',') \
.load("dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/data/data_by_year.csv")

# Convertendo o DataFrame do Spark para um DataFrame do Pandas
df_data_year = df_data_year.pandas_api()
# Convertendo as colunas selecionadas do DataFrame de string para float
df_data_year[['acousticness', 'danceability', 'duration_ms', 'energy', 'instrumentalness', 'liveness', 'loudness', 'speechiness', 'tempo', 'valence', 'popularity']] = df_data_year[['acousticness', 'danceability', 'duration_ms', 'energy', 'instrumentalness', 'liveness', 'loudness', 'speechiness', 'tempo', 'valence', 'popularity']].astype(float)

In [0]:
# Carregando o arquivo data_by_genres.csv utilizando o Spark
df_data_genderes = spark.read.format('csv') \
.option("inferSchema", 'True') \
.option("header", 'True') \
.option("sep", ',') \
.load("dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/data/data_by_genres.csv")

# Convertendo o DataFrame do Spark para um DataFrame do Pandas
df_data_genderes = df_data_genderes.pandas_api()
# Convertendo as colunas selecionadas do DataFrame de string para float
df_data_genderes[['acousticness', 'danceability', 'duration_ms', 'energy', 'instrumentalness', 'liveness', 'loudness', 'speechiness', 'tempo', 'valence', 'popularity']] = df_data_genderes[['acousticness', 'danceability', 'duration_ms', 'energy', 'instrumentalness', 'liveness', 'loudness', 'speechiness', 'tempo', 'valence', 'popularity']].astype(float)

In [0]:
# Carregando o arquivo data_by_artist.csv utilizando o Spark
df_Wgenres = spark.read.format('csv') \
.option("inferSchema", 'True') \
.option("header", 'True') \
.option("sep", ',') \
.load("dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/data/data_w_genres.csv")

# Convertendo o DataFrame do Spark para um DataFrame do Pandas
df_Wgenres = df_Wgenres.pandas_api()
# Convertendo as colunas selecionadas do DataFrame de string para float
df_Wgenres[['acousticness', 'danceability', 'duration_ms', 'energy', 'instrumentalness', 'liveness', 'loudness', 'speechiness', 'tempo', 'valence', 'popularity']] 
df_Wgenres[['acousticness', 'danceability', 'duration_ms', 'energy', 'instrumentalness', 'liveness', 'loudness', 'speechiness', 'tempo', 'valence', 'popularity']].astype(float)

,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity
0,0.590111,0.467222,2.503186e+05,0.394003,1.139985e-02,0.290833,-14.448000,0.210389,117.518111,0.389500,38.333333
1,0.862538,0.441731,2.872800e+05,0.406808,8.115826e-02,0.315215,-10.690000,0.176212,103.044154,0.268865,30.576923
2,0.856571,0.348286,3.289200e+05,0.286571,2.459295e-02,0.325786,-15.230714,0.118514,77.375857,0.354857,34.857143
3,0.884926,0.425074,2.628910e+05,0.245770,7.358728e-02,0.275481,-15.639370,0.123200,88.667630,0.372030,34.851852
4,0.510714,0.467143,2.704361e+05,0.488286,9.400291e-03,0.195000,-10.236714,0.098543,122.835857,0.482286,43.000000
5,0.609556,0.487278,2.050919e+05,0.309906,4.695657e-03,0.274767,-18.266389,0.098022,118.648944,0.441556,32.777778
6,0.725000,0.637000,1.355330e+05,0.512000,1.860000e-01,0.426000,-20.615000,0.210000,134.819000,0.885000,0.000000
7,0.927000,0.734000,1.756930e+05,0.474000,7.620000e-02,0.737000,-10.544000,0.256000,132.788000,0.902000,3.000000
8,0.173145,0.662787,2.189482e+05,0.695393,4.980262e-05,0.161102,-9.768705,0.084536,133.031180,0.751344,34.229508
9,0.544467,0.789800,1.379105e+05,0.532933,2.306258e-02,0.180300,-9.149267,0.293687,112.344800,0.480700,67.533333
10,0.239000,0.883000,1.415190e+05,0.625000,0.000000e+00,0.076500,-4.098000,0.245000,126.677000,0.871000,67.000000
11,0.000122,0.514000,3.312400e+05,0.899000,7.930000e-02,0.367000,-5.115000,0.060200,174.028000,0.266000,59.000000
12,0.148100,0.854000,1.905720e+05,0.683000,2.075000e-06,0.188500,-6.997000,0.221000,100.724500,0.625500,57.500000
13,0.141485,0.749344,1.463864e+05,0.635552,4.567510e-02,0.202253,-6.631304,0.156108,115.022024,0.287286,61.800000
14,0.624769,0.563615,3.140236e+05,0.457692,8.692308e-06,0.204385,-8.338462,0.152454,117.006846,0.467538,47.692308
15,0.553889,0.648444,3.042119e+05,0.441111,2.544444e-05,0.214667,-11.459778,0.495111,114.808444,0.524778,48.666667
16,0.604500,0.773500,3.617800e+05,0.309500,0.000000e+00,0.222200,-12.669000,0.289000,105.700000,0.596500,48.000000
17,0.105556,0.557125,2.552135e+05,0.612250,2.330025e-02,0.127588,-9.638125,0.032150,103.080250,0.532625,34.625000
18,0.847000,0.410000,3.118370e+05,0.169000,3.270000e-03,0.117000,-11.422000,0.048500,89.494000,0.208000,67.000000
19,0.538000,0.731000,3.614400e+05,0.794000,2.390000e-05,0.073600,-4.182000,0.040800,88.003000,0.873000,43.000000
20,0.011235,0.640500,1.969690e+05,0.800000,0.000000e+00,0.252000,-4.473500,0.048750,151.013250,0.375000,79.250000
21,0.011631,0.589200,2.536774e+05,0.879200,2.026000e-06,0.171120,-5.259800,0.172140,134.969400,0.427000,45.800000
22,0.191611,0.608743,2.367752e+05,0.694429,2.703210e-03,0.202860,-6.273800,0.057138,115.615886,0.564781,45.371429
23,0.012816,0.451500,2.052500e+05,0.883250,2.400000e-06,0.150700,-4.261750,0.079075,168.371250,0.391250,43.500000
24,0.008410,0.255000,2.736240e+05,0.858000,3.550000e-04,0.513000,-5.085000,0.069400,144.653000,0.237000,36.000000
25,0.000155,0.542000,2.260000e+05,0.894000,1.040000e-03,0.116000,-5.025000,0.053700,119.128000,0.336000,42.000000
26,0.122686,0.688429,2.203777e+05,0.586857,5.714286e-07,0.148186,-7.505286,0.058714,87.361286,0.372857,59.285714
27,0.011400,0.696000,3.981060e+05,0.667000,0.000000e+00,0.181000,-7.665000,0.040700,121.932000,0.287000,63.000000
28,0.021700,0.789000,2.362530e+05,0.793000,8.260000e-01,0.112000,-6.629000,0.107000,149.368000,0.743000,50.000000
29,0.110859,0.408429,2.098570e+05,0.748857,2.331786e-04,0.152986,-5.050857,0.044886,150.522714,0.328714,48.714286
30,0.190833,0.584476,2.360126e+05,0.542076,8.760404e-03,0.229705,-13.288048,0.037852,118.476095,0.573810,37.000000
31,0.158450,0.619250,1.266052e+05,0.595750,0.000000e+00,0.371750,-6.588000,0.212500,114.874750,0.781250,68.000000
32,0.588875,0.292525,1.731064e+05,0.397000,7.145375e-01,0.195375,-13.496375,0.037975,100.623125,0.391525,27.000000
33,0.230821,0.560632,2.987966e+05,0.567316,7.471384e-03,0.152095,-10.354053,0.066111,121.800263,0.555000,41.578947
34,0.270000,0.929000,1.823730e+05,0.661000,1.520000e-06,0.087900,-6.794000,0.171000,114.973000,0.708000,37.000000
35,0.138618,0.677417,2.705139e+05,0.533396,1.645317e-04,0.133806,-7.616583,0.106571,114.645271,0.551167,50.166667
36,0.991000,0.414000,1.377330e+05,0.018700,8.920000e-01,0.051300,-39.385000,0.055700,74.477000,0.195000,52.000000
37,0.080266,0.385833,2.042802e+05,0.888833,2.733333e-06,0.249233,-3.887000,0.069300,138.692167,0.450667,50.500000
38,0.104675,0.511750,1.554198e+05,0.771750,3.870000e-01,0.115800,-6.578000,0.076775,140.934000,0.764500,31.750000
39,0.670000,0.466333,4.261500e+04,0.874667,1.175682e-01,0.391000,-4.884000,0.216633,98.253667,0.658333,32.000000
40,0.891500,0.589500,1.932065e+05,0.402500,0.000000e+00,0.472500,-11.348500,0.172000,97.403500,0.594000,23.000000
41,0.080000,0.739000,1.134930e+05,0.518000,8.650000e-01,0.091700,-15.621000,0.097900,120.939000,0.222000,19.000000
42,0.418500,0.757000,1.407500e+05,0.605250,7.778500e-04,0.124250,-9.725750,0.044725,128.497500,0.899500,24.250000
43,0.319856,0.680000,2.746280e+05,0.612111,2.825717e-02,0.169333,-13.467889,0.031933,121.795222,0.834889,38.222222
44,0.735000,0.783000,1.708670e+05,0.380000,1.580000e-06,0.158000,-8.507000,0.097400,99.802000,0.840000,56.000000
45,0.037990,0.699000,2.576175e+05,0.947500,1.541665e-01,0.515500,-4.686500,0.053600,131.007500,0.689500,59.500000
46,0.135493,0.749315,2.356815e+05,0.650291,5.069163e-04,0.218785,-6.109748,0.222076,130.113772,0.496820,57.023622
47,0.001470,0.588000,1.835540e+05,0.788000,2.090000e-05,0.378000,-5.582000,0.034100,96.007000,0.382000,0.000000
48,0.071700,0.814000,9.360000e+04,0.879000,0.000000e+00,0.040100,-5.416000,0.120000,120.113000,0.962000,47.000000
49,0.078200,0.906000,3.385330e+05,0.382000,3.210000e-05,0.113000,-13.632000,0.282000,126.073000,0.630000,30.000000
50,0.071800,0.781000,2.441330e+05,0.838000,5.420000e-06,0.038100,-13.943000,0.049400,122.819000,0.849000,29.000000
51,0.052961,0.873095,2.334374e+05,0.660333,1.312112e-02,0.390152,-11.565857,0.186067,126.412952,0.610333,35.809524
52,0.004360,0.530000,2.740530e+05,0.745000,0.000000e+00,0.345000,-6.190000,0.106000,134.068000,0.269000,51.000000
53,0.030780,0.698250,2.282080e+05,0.921750,6.422350e-03,0.083525,-11.521750,0.059025,130.971500,0.768500,55.750000
54,0.034800,0.788000,1.428097e+06,0.687000,2.030000e-05,0.148000,-13.304000,0.152000,102.345000,0.897000,45.000000
55,0.002188,0.879333,2.357197e+05,0.791667,2.565000e-01,0.087600,-9.099000,0.062033,127.014667,0.821667,56.333333
56,0.044300,0.851000,4.034670e+05,0.451000,2.970000e-01,0.127000,-10.707000,0.267000,117.847000,0.250000,33.000000
57,0.000236,0.458000,2.577330e+05,0.541000,1.830000e-03,0.037100,-12.131000,0.048500,133.573000,0.577000,27.000000
58,0.905000,0.229000,2.678403e+05,0.155000,8.523333e-01,0.105267,-19.014333,0.035533,114.312000,0.063333,48.333333
59,0.475000,0.463000,2.186400e+05,0.402250,2.006925e-01,0.243750,-10.978500,0.030075,125.391250,0.405500,1.250000
60,0.995000,0.501000,1.894530e+05,0.341000,1.170000e-02,0.418000,-11.514000,0.081400,109.956000,0.621000,0.000000
61,0.831000,0.346667,1.014803e+05,0.326000,8.103333e-01,0.336767,-13.196000,0.036933,100.024333,0.632667,0.000000
62,0.131725,0.781764,2.152995e+05,0.553202,3.678730e-02,0.173996,-7.367921,0.284043,125.437820,0.338211,67.011236
63,0.948000,0.789000,2.780820e+05,0.352000,7.780000e-04,0.086700,-9.337000,0.660000,139.616000,0.659000,16.000000
64,0.000046,0.834000,3.097470e+05,0.605000,4.540000e-01,0.295000,-14.531000,0.248000,139.997000,0.515000,0.000000
65,0.281000,0.830000,1.907460e+05,0.574000,0.000000e+00,0.124000,-6.892000,0.701000,143.892000,0.538000,70.000000
66,0.206000,0.814000,2.302670e+05,0.680000,0.000000e+00,0.101000,-6.928000,0.043000,126.976000,0.963000,44.000000
67,0.059800,0.540500,1.978065e+05,0.740000,0.000000e+00,0.124350,-5.434500,0.180050,117.992500,0.340000,66.500000
68,0.144525,0.742947,1.628681e+05,0.655684,8.539196e-03,0.146674,-5.020053,0.112747,120.760632,0.545253,74.263158
69,0.428000,0.514000,1.558930e+05,0.712000,8.770000e-06,0.112000,-7.281000,0.334000,76.393000,0.487000,68.000000
70,0.015800,0.591000,2.830000e+05,0.602000,0.000000e+00,0.278000,-7.483000,0.386000,147.957000,0.355000,0.000000
71,0.603000,0.586500,2.530465e+05,0.499000,4.298400e-01,0.149000,-8.705000,0.040350,122.251000,0.600500,59.000000
72,0.291200,0.622500,1.477450e+05,0.418000,0.000000e+00,0.203000,-9.268500,0.479000,103.163000,0.402000,69.500000
73,0.085223,0.688000,2.176793e+05,0.732000,3.341333e-02,0.092800,-3.418333,0.038833,128.237000,0.590000,58.666667
74,0.176000,0.615000,2.008270e+05,0.901000,0.000000e+00,0.204000,-4.457000,0.030200,131.989000,0.779000,48.000000
75,0.133567,0.773393,2.625309e+05,0.704151,7.963721e-03,0.224101,-7.133066,0.223157,107.809790,0.607426,49.125000
76,0.093800,0.893000,2.938400e+05,0.576000,0.000000e+00,0.075800,-7.514000,0.357000,94.307000,0.861000,42.000000
77,0.100000,0.140000,2.045870e+05,0.478000,1.120000e-04,0.105000,-10.145000,0.048400,185.121000,0.041200,75.000000
78,0.605500,0.433000,1.690670e+05,0.376500,0.000000e+00,0.114800,-11.488500,0.027700,89.173000,0.442000,28.500000
79,0.001300,0.516000,2.470600e+05,0.452000,2.690000e-06,0.128000,-8.204000,0.032200,130.069000,0.041200,0.000000
80,0.046651,0.907143,2.258057e+05,0.533000,1.445714e-06,0.295429,-11.439571,0.224857,102.700857,0.766286,35.142857
81,0.589500,0.551500,3.458665e+05,0.639000,8.150000e-07,0.219500,-7.914500,0.046250,103.989500,0.622500,41.000000
82,0.075700,0.764000,2.146890e+05,0.403000,0.000000e+00,0.044300,-10.295000,0.358000,96.114000,0.349000,16.000000
83,0.040608,0.505863,2.329456e+05,0.789902,6.610647e-03,0.160898,-5.749569,0.038418,130.754059,0.451824,50.019608
84,0.000064,0.367000,2.711600e+05,0.961000,1.190000e-03,0.110000,-3.186000,0.080700,97.000000,0.237000,46.000000
85,0.479000,0.599000,2.028570e+05,0.471000,0.000000e+00,0.133000,-8.552000,0.094500,121.110000,0.547000,0.000000
86,0.020678,0.615736,2.095399e+05,0.824019,1.385628e-02,0.169638,-7.346491,0.065045,134.838321,0.618577,40.452830
87,0.671000,0.980000,1.801390e+05,0.413000,7.950000e-05,0.170000,-11.052000,0.101000,119.993000,0.764000,77.000000
88,0.113000,0.772000,2.895870e+05,0.615000,0.000000e+00,0.058100,-7.983000,0.063300,119.962000,0.704000,54.000000
89,0.001190,0.585000,1.986000e+05,0.931000,2.460000e-05,0.115000,-4.843000,0.084700,160.079000,0.814000,53.000000
90,0.029173,0.529077,2.542991e+05,0.621897,2.874001e-02,0.121656,-11.375436,0.032105,126.703128,0.778462,32.794872
91,0.149200,0.728500,2.113865e+05,0.916000,1.555000e-05,0.133000,-4.360000,0.183750,131.919000,0.858500,55.000000
92,0.183000,0.496000,2.104690e+05,0.789000,0.000000e+00,0.340000,-3.648000,0.083900,127.961000,0.286000,52.000000
93,0.055800,0.717800,2.720558e+05,0.719600,2.168000e-05,0.150580,-5.923800,0.110840,129.684800,0.667800,49.400000
94,0.020766,0.683750,1.936009e+05,0.793200,4.446900e-05,0.317150,-3.929750,0.178530,125.772650,0.549650,53.950000
95,0.349667,0.669667,3.207777e+05,0.435667,1.509667e-04,0.330667,-11.056000,0.034200,113.091000,0.479333,45.333333
96,0.016500,0.719000,3.584670e+05,0.686000,0.000000e+00,0.236000,-4.169000,0.082900,95.190000,0.490000,46.000000
97,0.159067,0.850333,2.455600e+05,0.665667,0.000000e+00,0.157867,-13.846000,0.253333,105.842333,0.650333,28.333333
98,0.007500,0.444000,2.498270e+05,0.859000,4.320000e-05,0.240000,-4.962000,0.048400,99.655000,0.394000,38.000000
99,0.021940,0.515000,2.575135e+05,0.966000,1.450000e-05,0.269500,-2.603000,0.069600,178.480000,0.811500,59.500000
100,0.184150,0.528667,2.396733e+05,0.570000,5.100000e-07,0.126633,-10.100500,0.038250,117.876500,0.446167,48.333333
101,0.749000,0.363000,1.620930e+05,0.388000,0.000000e+00,0.363000,-8.608000,0.034000,76.099000,0.348000,37.000000
102,0.010400,0.265500,1.580070e+05,0.929500,2.605000e-06,0.615500,-4.733000,0.125000,154.434500,0.498500,33.500000
103,0.002120,0.617000,1.904270e+05,0.790000,4.550000e-02,0.159000,-6.983000,0.036500,138.001000,0.267000,57.000000
104,0.010200,0.760000,3.110400e+05,0.585000,4.760000e-04,0.308000,-7.307000,0.161000,91.179000,0.455000,52.000000
105,0.196978,0.846889,1.757710e+05,0.566556,0.000000e+00,0.151467,-6.050556,0.340889,126.252667,0.339667,69.222222
106,0.885000,0.314000,3.010400e+05,0.395000,7.930000e-06,0.293000,-11.237000,0.053800,165.023000,0.362000,4.000000
107,0.016084,0.417500,1.627168e+05,0.791250,4.115020e-01,0.139525,-8.591750,0.066975,155.661500,0.647750,30.500000
108,0.784000,0.628000,2.569810e+05,0.091000,9.440000e-04,0.102000,-18.878000,0.039800,130.486000,0.152000,0.000000
109,0.282333,0.476333,2.906363e+05,0.487333,1.573783e-03,0.111333,-10.056333,0.030133,111.239667,0.311667,33.666667
110,0.005890,0.540000,1.924000e+05,0.929000,4.010000e-06,0.424000,-2.646000,0.278000,176.023000,0.624000,61.000000
111,0.043567,0.547308,1.955931e+05,0.804585,1.553015e-05,0.181711,-4.599892,0.104403,141.883923,0.520938,61.015385
112,0.122386,0.695039,2.349641e+05,0.762388,5.484753e-04,0.198361,-4.149427,0.259516,105.929427,0.589770,52.342697
113,0.791833,0.496167,1.680443e+05,0.286167,2.263800e-01,0.112467,-12.671167,0.033100,117.943667,0.496500,25.666667
114,0.016430,0.809000,2.124340e+05,0.624000,0.000000e+00,0.235500,-8.810000,0.256500,125.031500,0.532000,47.500000
115,0.996000,0.000000,1.976800e+05,0.019700,9.960000e-01,0.104000,-47.190000,0.000000,0.000000,0.000000,57.000000
116,0.227500,0.662500,2.110600e+05,0.597500,4.010470e-02,0.107650,-11.681500,0.029750,126.455500,0.722500,42.000000
117,0.158000,0.842000,3.521730e+05,0.336000,0.000000e+00,0.256000,-8.227000,0.379000,78.001000,0.599000,36.000000
118,0.224000,0.748000,1.719070e+05,0.660000,5.300000e-02,0.101000,-4.704000,0.048700,137.033000,0.328000,66.000000
119,0.032690,0.851000,2.562798e+05,0.742000,0.000000e+00,0.183450,-11.609250,0.223750,133.014250,0.679500,41.750000
120,0.266721,0.637130,2.202179e+05,0.520435,1.885923e-03,0.122970,-7.958130,0.160561,121.375630,0.308896,63.869565
121,0.443000,0.717500,2.959930e+05,0.473500,1.585740e-03,0.131000,-8.536500,0.030950,97.287500,0.470000,57.500000
122,0.112185,0.733731,1.562948e+05,0.697923,4.606538e-06,0.144331,-5.134038,0.240762,123.093385,0.455385,69.307692
123,0.128000,0.768000,2.145600e+05,0.725000,0.000000e+00,0.122000,-6.543000,0.292000,98.963000,0.794000,51.000000
124,0.140000,0.897000,1.616840e+05,0.413000,0.000000e+00,0.070800,-13.630000,0.122000,95.020000,0.369000,63.000000
125,0.000012,0.451000,1.892000e+05,0.908000,8.880000e-03,0.155000,-11.616000,0.062700,103.893000,0.398000,31.000000
126,0.000009,0.349000,1.673330e+05,0.709000,9.500000e-03,0.147000,-12.339000,0.033600,114.581000,0.708000,41.000000
127,0.197222,0.740000,2.559702e+05,0.611222,4.330793e-03,0.164422,-8.151889,0.065811,99.070333,0.590000,52.111111
128,0.064500,0.671000,2.855330e+05,0.707000,1.630000e-02,0.057000,-11.549000,0.033600,125.829000,0.599000,25.000000
129,0.762000,0.712000,1.151770e+05,0.818000,8.760000e-01,0.126000,-9.180000,0.047000,133.444000,0.975000,48.000000
130,0.008570,0.553500,2.851535e+05,0.871500,5.855000e-01,0.121500,-8.047500,0.059750,128.477500,0.502500,42.000000
131,0.137950,0.649000,1.958755e+05,0.643500,5.350000e-07,0.421000,-5.637000,0.280000,122.349500,0.500000,54.000000
132,0.016600,0.764000,1.808130e+05,0.672000,1.060000e-06,0.103000,-4.274000,0.065500,150.021000,0.594000,68.000000
133,0.527467,0.585000,2.094447e+05,0.463167,4.603500e-05,0.218150,-9.008667,0.091983,109.587833,0.385333,69.833333
134,0.073377,0.780538,2.823673e+05,0.664385,6.000000e-04,0.242385,-6.487769,0.184500,122.075923,0.539077,42.538462
135,0.030980,0.793267,3.110733e+05,0.622800,1.987389e-03,0.191207,-9.051500,0.263913,129.298833,0.601900,37.233333
136,0.103000,0.834000,6.005600e+04,0.375000,0.000000e+00,0.145000,-6.258000,0.391000,95.993000,0.389000,60.000000
137,0.463000,0.697000,9.601600e+04,0.480000,8.500000e-03,0.378000,-9.856000,0.049300,119.951000,0.176000,57.000000
138,0.952000,0.748000,1.262500e+05,0.265000,9.170000e-01,0.086600,-12.074000,0.229000,77.009000,0.140000,70.000000
139,0.637000,0.597000,2.488030e+05,0.559000,0.000000e+00,0.137000,-7.219000,0.083500,145.826000,0.268000,66.000000
140,0.139000,0.816000,1.481400e+05,0.577000,0.000000e+00,0.082700,-5.998000,0.410000,171.028000,0.459000,66.000000
141,0.179000,0.744000,3.404400e+05,0.797000,1.030000e-02,0.139000,-8.867000,0.037700,94.801000,0.954000,31.000000
142,0.347030,0.610250,2.505826e+05,0.581000,3.550000e-07,0.113165,-8.214250,0.041735,101.638800,0.427750,49.000000
143,0.545000,0.817000,2.316020e+05,0.487000,0.000000e+00,0.336000,-6.585000,0.474000,70.949000,0.650000,62.000000
144,0.072900,0.786000,1.571650e+05,0.854000,1.630000e-06,0.179000,-4.247000,0.052300,105.078000,0.687000,59.000000
145,0.030187,0.596000,2.170753e+05,0.631000,2.826676e-01,0.172300,-9.655333,0.048900,132.090667,0.514667,33.666667
146,0.033133,0.864333,1.812200e+05,0.544000,0.000000e+00,0.174600,-8.401333,0.272667,90.156667,0.521000,67.666667
147,0.404000,0.711000,2.171820e+05,0.545000,0.000000e+00,0.122000,-6.810000,0.032200,108.020000,0.345000,66.000000
148,0.232000,0.685000,2.590600e+05,0.518000,7.556600e-04,0.139550,-8.679000,0.228000,90.419500,0.529500,51.000000
149,0.218108,0.632333,1.465823e+05,0.670889,1.745843e-01,0.151989,-8.077222,0.042189,111.300667,0.805889,25.111111
150,0.198000,0.885000,3.071200e+05,0.598000,0.000000e+00,0.384000,-6.663000,0.372000,95.402000,0.779000,39.000000
151,0.253386,0.730093,2.004519e+05,0.626840,1.615733e-06,0.164903,-7.011053,0.229847,118.733867,0.500733,66.640000
152,0.132125,0.695000,3.446330e+05,0.933000,4.573000e-01,0.074750,-7.848000,0.063100,125.915500,0.582000,27.500000
153,0.026354,0.402596,2.077462e+05,0.916731,7.329885e-05,0.285265,-4.427519,0.111317,144.221462,0.458827,53.423077
154,0.014900,0.499000,3.101070e+05,0.706000,0.000000e+00,0.306000,-7.903000,0.033300,111.949000,0.414000,29.000000
155,0.947000,0.549000,2.688000e+05,0.240000,0.000000e+00,0.106000,-7.778000,0.033800,119.580000,0.167000,54.000000
156,0.025411,0.512667,2.433823e+05,0.725000,4.688957e-01,0.212695,-9.317571,0.037624,145.650190,0.697048,41.904762
157,0.012600,0.444000,3.118670e+05,0.592000,2.690000e-03,0.108000,-7.775000,0.039000,100.811000,0.253000,33.000000
158,0.625800,0.469500,2.438135e+05,0.374625,2.014425e-04,0.113625,-8.296750,0.043625,119.454125,0.227250,59.125000
159,0.030000,0.683000,2.671070e+05,0.789000,1.050000e-02,0.072400,-9.034000,0.060200,119.504000,0.657000,48.000000
160,0.854000,0.507000,1.461730e+05,0.255000,0.000000e+00,0.172000,-11.857000,0.065100,97.231000,0.438000,37.000000
161,0.955000,0.717000,1.789070e+05,0.178000,5.190000e-01,0.066300,-15.267000,0.060700,84.079000,0.479000,3.000000
162,0.833667,0.792667,1.699563e+05,0.285667,9.223333e-01,0.102833,-12.981333,0.063733,124.990667,0.316000,62.666667
163,0.754000,0.542000,1.379200e+05,0.730000,0.000000e+00,0.185000,-7.491000,0.030000,112.789000,0.960000,47.000000
164,0.109088,0.519525,2.510804e+05,0.622520,2.966383e-01,0.135864,-9.763203,0.055608,124.477102,0.256278,49.474576
165,0.597000,0.303000,2.158670e+05,0.400000,6.820000e-01,0.104000,-11.037000,0.031600,178.465000,0.474000,0.000000
166,0.136300,0.676000,1.828597e+05,0.612667,1.167333e-01,0.131300,-8.663333,0.060333,101.286000,0.228000,66.333333
167,0.203033,0.390667,2.109910e+05,0.615000,0.000000e+00,0.177333,-4.385000,0.029767,152.981667,0.341333,59.333333
168,0.001211,0.252750,2.103668e+05,0.927500,3.503950e-04,0.253900,-3.423250,0.094425,123.785000,0.306000,45.000000
169,0.000030,0.555000,2.002400e+05,0.980000,4.380000e-05,0.066100,-6.063000,0.154000,143.005000,0.370000,48.000000
170,0.326025,0.754750,2.808700e+05,0.538750,6.274750e-04,0.121125,-9.281500,0.057625,126.933250,0.749000,45.750000
171,0.017599,0.490500,2.053470e+05,0.806000,1.150000e-04,0.256500,-5.950500,0.033950,132.267000,0.473000,62.000000
172,0.314250,0.675500,1.811865e+05,0.917250,3.305500e-02,0.118750,-6.031750,0.030325,128.456000,0.605000,63.750000

In [0]:
df_Wgenres_spark = df_Wgenres.to_spark()  # Converte para Spark DataFrame

df_Wgenres_spark.write.mode("overwrite").parquet(
    "dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/df_Wgenres.parquet/"
)

In [0]:
# Carregando o arquivo data_by_artist.csv utilizando o Spark
df_data_artist = spark.read.format('csv') \
.option("inferSchema", 'True') \
.option("header", 'True') \
.option("sep", ',') \
.load("dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/data/data_by_artist.csv")

# Convertendo o DataFrame do Spark para um DataFrame do Pandas
df_data_artist = df_data_artist.pandas_api()
# Convertendo as colunas selecionadas do DataFrame de string para float
df_data_artist[['acousticness', 'danceability', 'duration_ms', 'energy', 'instrumentalness', 'liveness', 'loudness', 'speechiness', 'tempo', 'valence', 'popularity']] = df_data_artist[['acousticness', 'danceability', 'duration_ms', 'energy', 'instrumentalness', 'liveness', 'loudness', 'speechiness', 'tempo', 'valence', 'popularity']].astype(float)

In [0]:
dbutils.fs.mkdirs("dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/")

Out[129]: True

In [0]:
type(df_data_year)

Out[130]: pyspark.pandas.frame.DataFrame

In [0]:
dbutils.fs.ls("dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/data/")

Out[131]: [FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/data/data.csv', name='data.csv', size=29654587, modificationTime=1735929469000),
 FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/data/data_by_artist.csv', name='data_by_artist.csv', size=4315607, modificationTime=1735929454000),
 FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/data/data_by_genres.csv', name='data_by_genres.csv', size=576456, modificationTime=1735929456000),
 FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/data/data_by_year.csv', name='data_by_year.csv', size=21194, modificationTime=1735929457000),
 FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/data/data_w_genres.csv', name='data_w_genres.csv', size=5224673, modificationTime=1735929461000)]

In [0]:
dbutils.fs.ls("dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/")

Out[132]: [FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data.parquet/', name='data.parquet/', size=0, modificationTime=0),
 FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data_artist.parquet/', name='data_artist.parquet/', size=0, modificationTime=0),
 FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data_genres.parquet/', name='data_genres.parquet/', size=0, modificationTime=0),
 FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data_year.parquet/', name='data_year.parquet/', size=0, modificationTime=0),
 FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/df_Wgenres.parquet/', name='df_Wgenres.parquet/', size=0, modificationTime=0)]

In [0]:
type(df_data)

Out[133]: pyspark.pandas.frame.DataFrame

In [0]:
type(df_data_year)

Out[134]: pyspark.pandas.frame.DataFrame

In [0]:
df_data.to_parquet("dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data.parquet")
df_data_year.to_parquet("dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data_year.parquet")
df_data_genderes.to_parquet("dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data_genres.parquet")
df_Wgenres.to_parquet("dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/df_Wgenres.parquet")

In [0]:
dbutils.fs.ls("dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/")

Out[136]: [FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data.parquet/', name='data.parquet/', size=0, modificationTime=0),
 FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data_artist.parquet/', name='data_artist.parquet/', size=0, modificationTime=0),
 FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data_genres.parquet/', name='data_genres.parquet/', size=0, modificationTime=0),
 FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data_year.parquet/', name='data_year.parquet/', size=0, modificationTime=0),
 FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/df_Wgenres.parquet/', name='df_Wgenres.parquet/', size=0, modificationTime=0)]

In [0]:
import pyspark.pandas as ps

In [0]:
df_data_pq = ps.read_parquet("dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data.parquet") 
df_data_pq.head()

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
0,0.917,1970,0.096000,The Velvet Underground,0.624,201440,0.774,0,60ZyiL4lmWzZyGfqyECTqp,0.030900,7,0.0960,-10.391,1,Train Round the Bend - 2015 Remaster,24,1970,0.0315,117.006
1,0.511,1970,0.001900,Ten Years After,0.405,458463,0.543,0,6DYyyUdHzI6RdSx0swUR1i,0.720000,2,0.1860,-9.313,1,Love Like a Man - 2017 Remaster,34,1970-04-01,0.0290,107.598
2,0.466,1970,0.052800,The Mothers Of Invention,0.444,105587,0.568,0,6HJAS8XZO0ctUcN2KsbLRa,0.000010,11,0.5120,-8.800,0,Oh No,24,1970-08-10,0.0327,124.319
3,0.523,1970,0.081100,Three Dog Night,0.502,174707,0.669,0,7sZ74qmKb1nyGKUgHROJ1n,0.000945,7,0.0906,-11.725,1,One Man Band,19,1970-01-01,0.0912,121.089
4,0.501,1970,0.000128,The Rolling Stones,0.273,246413,0.866,0,095WtNlSHE8TMB2gQ1fdTx,0.790000,11,0.9610,-7.598,1,Street Fighting Man - Live,25,1970-09-04,0.0347,134.891

## Analise Exploratoria

In [0]:
df_data_pq.describe()

,valence,year,acousticness,danceability,duration_ms,energy,explicit,instrumentalness,key,liveness,loudness,mode,popularity,speechiness,tempo
count,170653.000000,170653.000000,170653.000000,170080.000000,1.704540e+05,1.705730e+05,170606.000000,170270.000000,170451.000000,170613.000000,170621.000000,170635.000000,169496.000000,170042.000000,170404.000000
mean,0.528587,1976.787241,0.502115,0.537640,2.304044e+05,5.332695e+02,161.708058,36.464539,20.310635,3.575240,-11.417018,7.382782,31.543547,5.064387,118.226091
std,0.263171,25.917853,0.376032,0.175959,1.263665e+05,1.350096e+04,6984.208830,3139.122132,2119.315151,981.333683,5.729827,1867.348785,21.803031,98.121279,67.002730
min,0.000000,1921.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,-60.000000,-36.000000,-39.000000,-30.073000,-8.331000
25%,0.317000,1956.000000,0.101000,0.416000,1.695350e+05,2.560000e-01,0.000000,0.000000,2.000000,0.098700,-14.584000,0.000000,12.000000,0.034900,93.206000
50%,0.539000,1977.000000,0.516000,0.548000,2.072000e+05,4.730000e-01,0.000000,0.000215,5.000000,0.136000,-10.549000,1.000000,34.000000,0.045000,114.636000
75%,0.747000,1999.000000,0.893000,0.668000,2.621550e+05,7.050000e-01,0.000000,0.102000,8.000000,0.262000,-7.146000,1.000000,48.000000,0.076200,135.552000
max,1.000000,2020.000000,0.996000,0.988000,5.403500e+06,1.622000e+06,693933.000000,475880.000000,503320.000000,290627.000000,11.000000,701187.000000,100.000000,2009.000000,2010.000000

In [0]:
len(df_data_pq.year.unique())

Out[140]: 100

In [0]:
df_data_pq.year.value_counts()

Out[141]: 2018    2103
2020    2030
2011    2017
2010    2016
2014    2005
2001    2005
1990    2000
1975    2000
1977    2000
1974    2000
1955    2000
1978    2000
1952    2000
1956    2000
1997    2000
1994    2000
1968    2000
1951    2000
1973    2000
1979    2000
1971    2000
1950    2000
1949    2000
1966    2000
1969    2000
1982    2000
1945    2000
1989    2000
1996    2000
1998    2000
1963    2000
1985    2000
1970    2000
1995    2000
1972    2000
1992    2000
1958    2000
1983    2000
1954    2000
1984    2000
1981    2000
1986    2000
1976    2000
1940    2000
2002    2000
1993    2000
1967    1999
2017    1992
2013    1976
2015    1974
2004    1966
2009    1960
2000    1956
2008    1955
2003    1954
1999    1951
1959    1950
2007    1950
2006    1950
1988    1950
1991    1950
1957    1950
1965    1950
1987    1950
1980    1950
1953    1950
2005    1950
1964    1950
2019    1949
2012    1945
1930    1924
1961    1900
1948    1900
1962    1900
1960    1850
2016    1797
1946    1724
1942    1682
1947    1650
1935    1518
1926    1378
1928    1261
1936    1100
1939    1000
1931     966
1941     960
1929     952
1944     752
1943     710
1933     691
1937     657
1927     615
1938     613
1934     578
1932     502
1925     278
1924     236
1923     185
1921     150
1922      71
Name: year, dtype: int64

In [0]:
df_data_pq.year.value_counts().sort_index()

Out[34]: 1921     150
1922      71
1923     185
1924     236
1925     278
1926    1378
1927     615
1928    1261
1929     952
1930    1924
1931     966
1932     502
1933     691
1934     578
1935    1518
1936    1100
1937     657
1938     613
1939    1000
1940    2000
1941     960
1942    1682
1943     710
1944     752
1945    2000
1946    1724
1947    1650
1948    1900
1949    2000
1950    2000
1951    2000
1952    2000
1953    1950
1954    2000
1955    2000
1956    2000
1957    1950
1958    2000
1959    1950
1960    1850
1961    1900
1962    1900
1963    2000
1964    1950
1965    1950
1966    2000
1967    1999
1968    2000
1969    2000
1970    2000
1971    2000
1972    2000
1973    2000
1974    2000
1975    2000
1976    2000
1977    2000
1978    2000
1979    2000
1980    1950
1981    2000
1982    2000
1983    2000
1984    2000
1985    2000
1986    2000
1987    1950
1988    1950
1989    2000
1990    2000
1991    1950
1992    2000
1993    2000
1994    2000
1995    2000
1996    2000
1997    2000
1998    2000
1999    1951
2000    1956
2001    2005
2002    2000
2003    1954
2004    1966
2005    1950
2006    1950
2007    1950
2008    1955
2009    1960
2010    2016
2011    2017
2012    1945
2013    1976
2014    2005
2015    1974
2016    1797
2017    1992
2018    2103
2019    1949
2020    2030
Name: year, dtype: int64

In [0]:
df_data_pq.year.value_counts().sort_index().plot.bar()

In [0]:
df_data_pq['decade'] = df_data_pq.year.apply(lambda year: f'{(year//10)*10}s')

In [0]:
df_data_pq.head()

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo,decade
0,0.917,1970,0.096000,The Velvet Underground,0.624,201440,0.774,0,60ZyiL4lmWzZyGfqyECTqp,0.030900,7,0.0960,-10.391,1,Train Round the Bend - 2015 Remaster,24,1970,0.0315,117.006,1970s
1,0.511,1970,0.001900,Ten Years After,0.405,458463,0.543,0,6DYyyUdHzI6RdSx0swUR1i,0.720000,2,0.1860,-9.313,1,Love Like a Man - 2017 Remaster,34,1970-04-01,0.0290,107.598,1970s
2,0.466,1970,0.052800,The Mothers Of Invention,0.444,105587,0.568,0,6HJAS8XZO0ctUcN2KsbLRa,0.000010,11,0.5120,-8.800,0,Oh No,24,1970-08-10,0.0327,124.319,1970s
3,0.523,1970,0.081100,Three Dog Night,0.502,174707,0.669,0,7sZ74qmKb1nyGKUgHROJ1n,0.000945,7,0.0906,-11.725,1,One Man Band,19,1970-01-01,0.0912,121.089,1970s
4,0.501,1970,0.000128,The Rolling Stones,0.273,246413,0.866,0,095WtNlSHE8TMB2gQ1fdTx,0.790000,11,0.9610,-7.598,1,Street Fighting Man - Live,25,1970-09-04,0.0347,134.891,1970s

In [0]:
df_valida = df_data_pq[['decade']]
df_valida['qtd'] = 1

In [0]:
df_valida = df_valida.groupby('decade').sum()

Analise por Decada

In [0]:
df_valida.sort_index().plot.bar(y = 'qtd')

In [0]:
dbutils.fs.ls("dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/")

Out[41]: [FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data.parquet/', name='data.parquet/', size=0, modificationTime=0),
 FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data_artist.parquet/', name='data_artist.parquet/', size=0, modificationTime=0),
 FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data_genres.parquet/', name='data_genres.parquet/', size=0, modificationTime=0),
 FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data_year.parquet/', name='data_year.parquet/', size=0, modificationTime=0)]

In [0]:
path = 'dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data_year.parquet'
df_data_year = ps.read_parquet(path)
df_data_year.head()

,mode,year,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key
0,1,1921,0.886896,0.418597,260537.166667,0.231815,0.344878,0.205710,-17.048667,0.073662,101.531493,0.379327,0.653333,2
1,1,1922,0.938592,0.482042,165469.746479,0.237815,0.434195,0.240720,-19.275282,0.116655,100.884521,0.535549,0.140845,10
2,1,1923,0.957247,0.577341,177942.362162,0.262406,0.371733,0.227462,-14.129211,0.093949,114.010730,0.625492,5.389189,0
3,1,1924,0.940200,0.549894,191046.707627,0.344347,0.581701,0.235219,-14.231343,0.092089,120.689572,0.663725,0.661017,10
4,1,1925,0.962607,0.573863,184986.924460,0.278594,0.418297,0.237668,-14.146414,0.111918,115.521921,0.621929,2.604317,5

In [0]:
df_data_year.plot.line(x='year',y='duration_ms')

In [0]:
df_data_year.plot.line(x='year', y=['acousticness', 'danceability', 'energy',
       'instrumentalness', 'liveness', 'speechiness', 'valence'])

In [0]:
df_data_year['decade'] = df_data_year.year.apply(lambda year: f'{(year//10)*10}s')
df_data_year['qtd'] = 1

In [0]:
df_year_2 = df_data_year.groupby('decade').agg({
    'acousticness': 'mean',
    'danceability': 'mean',
    'duration_ms': 'mean',
    'energy': 'mean',
    'instrumentalness': 'mean',
    'liveness': 'mean',
    'loudness': 'mean',
    'speechiness': 'mean', 
    'tempo': 'mean',
    'valence': 'mean', 
    'popularity': 'mean',
    'qtd': 'sum' }).sort_index().reset_index()

In [0]:
df_year_2.plot.line(x='decade', y=['acousticness', 'danceability', 'energy',
       'instrumentalness', 'liveness', 'speechiness', 'valence'])

- Quais são os top 10 artistas?
- Qual o gênero musical desses top 10 artistas?
- Quais são os top gêneros?
- Quais são os artistas que estão nesses top gêneros?

In [0]:
dbutils.fs.ls("dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/")

Out[47]: [FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data.parquet/', name='data.parquet/', size=0, modificationTime=0),
 FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data_artist.parquet/', name='data_artist.parquet/', size=0, modificationTime=0),
 FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data_genres.parquet/', name='data_genres.parquet/', size=0, modificationTime=0),
 FileInfo(path='dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data_year.parquet/', name='data_year.parquet/', size=0, modificationTime=0)]

In [0]:
df_genres = ps.read_parquet('dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data_genres.parquet')
df_artists = ps.read_parquet('dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data_artist.parquet')

In [0]:
display(dbutils.fs.ls("dbfs:/FileStore/tables/arquivo_curso/"))
display(dbutils.fs.ls("dbfs:/FileStore/tables/arquivo_curso/dados/"))
display(dbutils.fs.ls("dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/"))
display(dbutils.fs.ls("dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/"))

path,name,size,modificationTime
dbfs:/FileStore/tables/arquivo_curso/Base_nacional_SB.json,Base_nacional_SB.json,129046,1725924114000
dbfs:/FileStore/tables/arquivo_curso/dados/,dados/,0,0

path,name,size,modificationTime
dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/,Spotify_Dataset/,0,0

path,name,size,modificationTime
dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/,dados_tratados/,0,0
dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/data/,data/,0,0

path,name,size,modificationTime
dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data.parquet/,data.parquet/,0,0
dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data_artist.parquet/,data_artist.parquet/,0,0
dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data_genres.parquet/,data_genres.parquet/,0,0
dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/data_year.parquet/,data_year.parquet/,0,0
dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/df_Wgenres.parquet/,df_Wgenres.parquet/,0,0

In [0]:
display(dbutils.fs.ls("dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/df_Wgenres.parquet/"))

path,name,size,modificationTime
dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/df_Wgenres.parquet/_started_7188614899077034872,_started_7188614899077034872,0,1740698492000

In [0]:
dbutils.fs.rm("dbfs:/FileStore/tables/arquivo_curso/dados/Spotify_Dataset/dados_tratados/df_Wgenres.parquet/", True)

Out[88]: False

In [0]:
df_Wgenres

,genres,artists,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key,mode,count
0,['show tunes'],"""""""Cats"""" 1981 Original London Cast""",0.5901111111111111,0.4672222222222222,250318.5555555556,0.3940033333333333,0.011399851111111107,0.2908333333333333,-14.448000,0.210389,117.518111,0.389500,38.333333,5.0,1.0,9.0
1,[],"""""""Cats"""" 1983 Broadway Cast""",0.8625384615384617,0.4417307692307693,287280.0,0.4068076923076923,0.08115826423076923,0.3152153846153846,-10.690000,0.176212,103.044154,0.268865,30.576923,5.0,1.0,26.0
2,[],"""""""Fiddler On The Roof” Motion Picture Chorus""",0.8565714285714285,0.34828571428571425,328920.0,0.2865714285714285,0.024592948571428568,0.3257857142857143,-15.230714,0.118514,77.375857,0.354857,34.857143,0.0,1.0,7.0
3,[],"""""""Fiddler On The Roof” Motion Picture Orchestra""",0.884925925925926,0.4250740740740739,262890.96296296304,0.2457703703703704,0.07358727925925927,0.2754814814814815,-15.639370,0.123200,88.667630,0.372030,34.851852,0.0,1.0,27.0
4,[],"""""""Joseph And The Amazing Technicolor Dreamcoa...",0.5107142857142857,0.4671428571428572,270436.14285714284,0.4882857142857143,0.00940029142857143,0.195,-10.236714,0.098543,122.835857,0.482286,43.000000,5.0,1.0,7.0

In [0]:
df_artists.head()

,mode,count,acousticness,artists,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key
0,1,9,0.590111,"""""""Cats"""" 1981 Original London Cast""",0.467222,250318.555556,0.394003,0.011400,0.290833,-14.448000,0.210389,117.518111,0.389500,38.333333,5
1,1,26,0.862538,"""""""Cats"""" 1983 Broadway Cast""",0.441731,287280.000000,0.406808,0.081158,0.315215,-10.690000,0.176212,103.044154,0.268865,30.576923,5
2,1,7,0.856571,"""""""Fiddler On The Roof” Motion Picture Chorus""",0.348286,328920.000000,0.286571,0.024593,0.325786,-15.230714,0.118514,77.375857,0.354857,34.857143,0
3,1,27,0.884926,"""""""Fiddler On The Roof” Motion Picture Orchestra""",0.425074,262890.962963,0.245770,0.073587,0.275481,-15.639370,0.123200,88.667630,0.372030,34.851852,0
4,1,7,0.510714,"""""""Joseph And The Amazing Technicolor Dreamcoa...",0.467143,270436.142857,0.488286,0.009400,0.195000,-10.236714,0.098543,122.835857,0.482286,43.000000,5

In [0]:
artistas_ordenado = df_artists.sort_values(by='count',ascending=False)
artistas_ordenado.head()

,mode,count,acousticness,artists,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key
8367,1,3169,0.984282,Francisco Canaro,0.659676,176986.345850,0.287555,0.537988,0.199492,-12.043738,0.110533,122.743169,0.745212,0.061849,2
28561,1,2422,0.353916,Эрнест Хемингуэй,0.696773,115936.962015,0.188971,0.000027,0.373329,-18.237630,0.926229,111.847911,0.583885,0.066061,11
28560,1,2136,0.297365,Эрих Мария Ремарк,0.693738,121013.185393,0.200289,0.000230,0.195630,-19.259112,0.921277,110.717091,0.536381,0.000000,0
8434,1,1459,0.738865,Frank Sinatra,0.385232,189282.134339,0.236152,0.021148,0.230828,-14.335969,0.049029,109.394801,0.364991,28.658670,5
10714,1,1256,0.985169,Ignacio Corsini,0.545475,154560.711783,0.187842,0.425159,0.182707,-20.862591,0.121051,106.514583,0.638670,0.031847,5

In [0]:
top_artistas = artistas_ordenado.iloc[0:10]
top_artistas

,mode,count,acousticness,artists,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key
8367,1,3169,0.984282,Francisco Canaro,0.659676,176986.345850,0.287555,0.537988,0.199492,-12.043738,0.110533,122.743169,0.745212,0.061849,2
28561,1,2422,0.353916,Эрнест Хемингуэй,0.696773,115936.962015,0.188971,0.000027,0.373329,-18.237630,0.926229,111.847911,0.583885,0.066061,11
28560,1,2136,0.297365,Эрих Мария Ремарк,0.693738,121013.185393,0.200289,0.000230,0.195630,-19.259112,0.921277,110.717091,0.536381,0.000000,0
8434,1,1459,0.738865,Frank Sinatra,0.385232,189282.134339,0.236152,0.021148,0.230828,-14.335969,0.049029,109.394801,0.364991,28.658670,5
10714,1,1256,0.985169,Ignacio Corsini,0.545475,154560.711783,0.187842,0.425159,0.182707,-20.862591,0.121051,106.514583,0.638670,0.031847,5
27109,1,1200,0.990092,Vladimir Horowitz,0.343624,266650.370833,0.118341,0.879898,0.182788,-23.190868,0.043228,94.845258,0.224994,3.694167,1
1682,1,1146,0.917843,Arturo Toscanini,0.315980,309308.737347,0.203463,0.474637,0.280793,-17.185234,0.058348,102.235789,0.283423,0.240838,0
2707,1,1103,0.908776,Billie Holiday,0.571550,185677.068903,0.202251,0.013111,0.217323,-13.221339,0.062274,109.883821,0.498693,16.780598,5
12378,1,1061,0.688296,Johnny Cash,0.620759,164491.506126,0.443462,0.017630,0.239843,-11.663137,0.095992,114.508436,0.672277,26.914232,10
7426,1,1023,0.738890,Elvis Presley,0.493966,157592.318671,0.424834,0.053483,0.245853,-12.921860,0.057361,112.397270,0.617856,34.019550,0

In [0]:
plot_title = 'Top 10 Artistas'
top_artistas.plot.bar(x='count',y='artists',title= plot_title)

In [0]:
lista_artistas = top_artistas.artists.unique().to_list()
lista_artistas

Out[57]: ['Francisco Canaro',
 'Эрнест Хемингуэй',
 'Эрих Мария Ремарк',
 'Frank Sinatra',
 'Ignacio Corsini',
 'Vladimir Horowitz',
 'Arturo Toscanini',
 'Billie Holiday',
 'Johnny Cash',
 'Elvis Presley']

In [0]:
df_Wgenres.head()

,genres,artists,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key,mode,count,qtd
0,['show tunes'],"""""""Cats"""" 1981 Original London Cast""",0.5901111111111111,0.4672222222222222,250318.5555555556,0.3940033333333333,0.011399851111111107,0.2908333333333333,-14.448000,0.210389,117.518111,0.389500,38.333333,5.0,1.0,9.0,1
1,[],"""""""Cats"""" 1983 Broadway Cast""",0.8625384615384617,0.4417307692307693,287280.0,0.4068076923076923,0.08115826423076923,0.3152153846153846,-10.690000,0.176212,103.044154,0.268865,30.576923,5.0,1.0,26.0,1
2,[],"""""""Fiddler On The Roof” Motion Picture Chorus""",0.8565714285714285,0.34828571428571425,328920.0,0.2865714285714285,0.024592948571428568,0.3257857142857143,-15.230714,0.118514,77.375857,0.354857,34.857143,0.0,1.0,7.0,1
3,[],"""""""Fiddler On The Roof” Motion Picture Orchestra""",0.884925925925926,0.4250740740740739,262890.96296296304,0.2457703703703704,0.07358727925925927,0.2754814814814815,-15.639370,0.123200,88.667630,0.372030,34.851852,0.0,1.0,27.0,1
4,[],"""""""Joseph And The Amazing Technicolor Dreamcoa...",0.5107142857142857,0.4671428571428572,270436.14285714284,0.4882857142857143,0.00940029142857143,0.195,-10.236714,0.098543,122.835857,0.482286,43.000000,5.0,1.0,7.0,1

In [0]:
df_Wgenres['qtd'] = 1  # Cria uma coluna de quantidade de 1 para cada linha
df_Wgenres_2 = df_Wgenres[['genres', 'qtd']]  # Seleciona apenas as colunas de gênero e quantidade
Wgenres_2_ordenado = df_Wgenres_2.groupby('genres').sum().sort_values(by='qtd', ascending=False).reset_index() # Agrupa os dados por gênero e soma a quantidade de músicas de cada gênero, em seguida ordena os resultados em ordem decrescente
top_generos = Wgenres_2_ordenado.loc[0:10] # Seleciona os 10 gêneros mais populares

plot_title = 'Top 10 Gêneros'
top_generos.plot.bar(x='qtd', y='genres', title=plot_title) # Plota um gráfico de barras para os top 10 gêneros

top_generos_2 = Wgenres_2_ordenado.loc[1:11] # Seleciona os gêneros do 2º ao 11º mais populares

plot_title = 'Top 10 Gêneros'
top_generos_2.plot.bar(x='qtd', y='genres', title=plot_title) # Plota um gráfico de barras para os gêneros do 2º ao 11º mais populares

In [0]:
lista_genero =  top_generos_2.genres.unique().to_list()
genero_artista = df_Wgenres.loc[df_Wgenres['genres'].isin (lista_genero)]
genero_artista = genero_artista[['genres', 'artists' ]]
display(genero_artista)

genres,artists
['show tunes'],"""""""Cats"""" 1981 Original London Cast"""
"['broadway', 'hollywood', 'show tunes']",'Legally Blonde' Ensemble
['show tunes'],'Legally Blonde' Greek Chorus
"['broadway', 'hollywood', 'show tunes']",Aaron Tveit
"['broadway', 'hollywood', 'show tunes']",Adam Pascal
['movie tunes'],Adriana Caselotti
['classical soprano'],Adrianne Pieczonka
['classical soprano'],Agnes Giebel
['gospel'],Albertina Walker
"['broadway', 'hollywood', 'show tunes']",Alex Brightman
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",Alex Gargolas
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",Alexis y Fido
"['broadway', 'hollywood', 'show tunes']",Alice Ripley
['movie tunes'],Alice Sixer
['show tunes'],Amanda Bynes
['show tunes'],Amy Spanger
['show tunes'],Andrea Burns
['classical soprano'],Andrea Rost
['orchestral performance'],André Cluytens
['orchestral performance'],André Previn
['show tunes'],Angela Cartwright
['classical soprano'],Anna Tomowa-Sintow
"['broadway', 'hollywood', 'show tunes']",Annaleigh Ashford
['classical soprano'],Anneliese Rothenberger
['gospel'],Anthony Brown & group therAPy
['movie tunes'],Anthony Gonzalez
"['broadway', 'hollywood', 'show tunes']",Anthony Rapp
['orchestral performance'],Antoni Wit
['hollywood'],Antonio Banderas
['movie tunes'],Ashley Lilley
['classical soprano'],Astrid Varnay
['show tunes'],Austyn Johnson
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",Baby Rasta
['sleep'],Baby Sleep
['sleep'],Baby Sweet Dream
"['broadway', 'hollywood', 'show tunes']",Barrett Wilbert Weed
['hollywood'],Barry Bostwick
"['disney', 'movie tunes']",Beaumont
['gospel'],Bebe & Cece Winans
"['broadway', 'hollywood', 'show tunes']",Bebe Neuwirth
['gospel'],Bebe Winans
['sleep'],Bedtime Baby
"['broadway', 'hollywood', 'show tunes']",Ben Fankhauser
['show tunes'],Benjamin Schrader
"['contemporary country', 'country', 'country road', 'modern country rock']",Bent
"['broadway', 'hollywood', 'show tunes']",Bernadette Peters
"['disney', 'movie tunes']",Beth Fowler
['movie tunes'],Betty Noyes
['classical soprano'],Bidu Sayão
"['contemporary country', 'country', 'country road', 'modern country rock']",Big & Rich
['movie tunes'],Bill Farmer
"['disney', 'movie tunes']",Bill Shirley
"['disney', 'movie tunes']",Bill Thompson
['movie tunes'],Billy Bletcher
"['contemporary country', 'country', 'country road', 'modern country rock']",Billy Currington
"['broadway', 'hollywood', 'show tunes']",Billy Porter
['gospel'],"Bishop Paul S. Morton, Sr."
"['disney', 'movie tunes']",Bobby Driscoll
['hollywood'],Bonham
['movie tunes'],Brad Garrett
"['disney', 'movie tunes']",Brad Kane
['hollywood'],Bradley Cooper
"['contemporary country', 'country', 'country road', 'modern country rock']",Brett Eldredge
['gospel'],Brian Courtney Wilson
"['broadway', 'hollywood', 'show tunes']",Brian D'Arcy James
['show tunes'],Brian Sears
['gospel'],Brian Wilson
['hollywood'],Brittany Snow
['movie tunes'],Bruce Adler
"['disney', 'movie tunes']",Bruce Reitherman
['hollywood'],Bruce Willis
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",Brytiago
"['contemporary country', 'country', 'country road', 'modern country rock']",Bucky Covington
['movie tunes'],Burke Moses
['sleep'],Calming Sounds
['movie tunes'],Cameron Seely
"['disney', 'movie tunes']",Carmen Twillie
"['broadway', 'hollywood', 'show tunes']",Caroline O'Connor
"['broadway', 'hollywood', 'show tunes']",Carrie Fletcher
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",Casa De Leones
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",Casper Magico
['movie tunes'],Cast - The Nightmare Before Christmas
['hollywood'],Cast Of Mamma Mia The Movie
['gospel'],CeCe Winans
"['contemporary country', 'country', 'country road', 'modern country rock']",Chase
"['contemporary country', 'country', 'country road', 'modern country rock']",Chase Rice
"['disney', 'movie tunes']",Cheryl Freeman
['movie tunes'],Childrens Chorus
"['disney', 'movie tunes']",Chorus
"['disney', 'movie tunes']",Chorus - Aladdin And The King Of Thieves
"['disney', 'movie tunes']",Chorus - Hercules
"['disney', 'movie tunes']",Chorus - Mulan
"['contemporary country', 'country', 'country road', 'modern country rock']",Chris Cagle
"['contemporary country', 'country', 'country road', 'modern country rock']",Chris Janson
"['contemporary country', 'country', 'country road', 'modern country rock']",Chris Young
['hollywood'],Christian Bale
"['broadway', 'hollywood', 'show tunes']",Christian Borle
['hollywood'],Christine Baranski
"['broadway', 'hollywood', 'show tunes']",Christopher Fitzgerald
"['broadway', 'hollywood', 'show tunes']",Christy Altomare
"['disney', 'movie tunes']",Cinderella's Mice Chorus
['hollywood'],Cindy Bullens
['show tunes'],Clark Johnsen
"['contemporary country', 'country', 'country road', 'modern country rock']",Clay Walker
['movie tunes'],Cliff Edwards
"['contemporary country', 'country', 'country road', 'modern country rock']",Cole Swindell
['hollywood'],Colin Firth
['gospel'],Commissioned
"['contemporary country', 'country', 'country road', 'modern country rock']",Corey Smith
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",Cosculluela
['classical soprano'],Cristina Deutekom
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",DJ Luian
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",DJ Nelson
['hollywood'],Dana Fuchs
"['broadway', 'hollywood', 'show tunes']",Daniel Breaker
['show tunes'],Daniel Everidge
['orchestral performance'],Daniel Harding
"['broadway', 'hollywood', 'show tunes']",Danny Burstein
['movie tunes'],Danny DeVito
['show tunes'],Daphne Rubin-Vega
"['contemporary country', 'country', 'country road', 'modern country rock']",Darryl Worley
['gospel'],Daryl Coley
"['disney', 'movie tunes']",Daughters of Triton
['orchestral performance'],David Lloyd-Jones
['movie tunes'],David Moscow
"['disney', 'movie tunes']",David Ogden Stiers
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",De La Ghetto
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",De Leone
['gospel'],DeWayne Woods
['show tunes'],Debbie Deb
['show tunes'],Debbie Turner
['sleep'],Deep Sleep
['sleep'],Deep Sleep Music Collective
['sleep'],Deep Sleep Music Experience
['show tunes'],Deidre Goodwin
['gospel'],Deitrick Haddon
['show tunes'],Delta Nus
['classical soprano'],Denise Duval
['show tunes'],Denise Faye
['show tunes'],Dequina Moore
"['disney', 'movie tunes']",Dickie Jones
"['contemporary country', 'country', 'country road', 'modern country rock']",Dierks Bentley
['movie tunes'],Digby Wolfe
['movie tunes'],Dominic Cooper
['gospel'],Donald Lawrence & The Tri-City Singers
"['disney', 'movie tunes']",Donna Murphy
['gospel'],Donnie McClurkin
['movie tunes'],Dora Luz
"['broadway', 'hollywood', 'show tunes']",Drew Gehling
['show tunes'],Duane Chase
['show tunes'],Duffy
"['contemporary country', 'country', 'country road', 'modern country rock']",Dust
"['contemporary country', 'country', 'country road', 'modern country rock']",Dustin Lynch
"['contemporary country', 'country', 'country road', 'modern country rock']",Dylan Scott
"['contemporary country', 'country', 'country road', 'modern country rock']",Easton Corbin
['classical soprano'],Eileen Farrell
['show tunes'],Ekaterina Chtchelkanova
['classical soprano'],Eleanor Steber
['classical soprano'],Elisabeth Grümmer
['classical soprano'],Elizabeth Harwood
['show tunes'],Elle McLemore
['hollywood'],Emma Stone
['movie tunes'],Ensemble
"['contemporary country', 'country', 'country road', 'modern country rock']",Eric
"['contemporary country', 'country', 'country road', 'modern country rock']",Eric Church
['classical soprano'],Erna Berger
"['disney', 'movie tunes']",Ernie
"['disney', 'movie tunes']",Ernie Sabella
['orchestral performance'],Eugen Jochum
['classical soprano'],Eva Marton
['hollywood'],Evan Rachel Wood
['hollywood'],Ewan McGregor
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",FLOW
['orchestral performance'],Fabien Gabel
['sleep'],Fan Sounds
['hollywood'],Felicia Day
['movie tunes'],Fess Parker
['gospel'],Forever Jones
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']","""Franco """"El Gorilla"""""""
"['disney', 'movie tunes']",Frank Churchill
"['contemporary country', 'country', 'country road', 'modern country rock']",Frankie Ballard
['orchestral performance'],Franz Welser-Möst
['gospel'],Fred Hammond
['classical soprano'],Galina Vishnevskaya
"['contemporary country', 'country', 'country road', 'modern country rock']",Gary Allan
['show tunes'],Gary Beach
"['disney', 'movie tunes']",George Bruns
['movie tunes'],George Givot
['movie tunes'],Gerard Butler
['show tunes'],Gerard Canonico
['orchestral performance'],Giuseppe Sinopoli
['gospel'],Gods Property
['show tunes'],Graham Bowen
['orchestral performance'],Grant Llewellyn
['gospel'],Group Therapy
['hollywood'],Haley Bennett
['movie tunes'],Harry Stockwell
['movie tunes'],Hayley Mills
['show tunes'],Heather Menzies
"['disney', 'movie tunes']",Heidi Mollenhauer
['orchestral performance'],Heinz Rögner
['hollywood'],Helena Bonham Carter
['classical soprano'],Helga Dernesch
['orchestral performance'],Helmuth Rilling
['orchestral performance'],Herbert Blomstedt
['gospel'],Hezekiah Walker
['gospel'],Hezekiah Walker & The Love Fellowship Crusade Choir
['show tunes'],Hilton McRae
['movie tunes'],Howard Ashman
['hollywood'],Hugh Grant
['movie tunes'],Ilene Woods
['classical soprano'],Inge Borkh
['classical soprano'],Irmgard Seefried
['orchestral performance'],István Kertész
"['disney', 'movie tunes']",J. Pat O'Malley
['hollywood'],J. Phoenix
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",Jadiel
"['contemporary country', 'country', 'country road', 'modern country rock']",Jake Owen
['movie tunes'],James Baskett
['orchestral performance'],James Conlon
['orchestral performance'],James Judd
['hollywood'],James Marsden
"['contemporary country', 'country', 'country road', 'modern country rock']",James Otto
['hollywood'],Jamie Campbell Bower
['classical soprano'],Jane Eaglen
['show tunes'],Janet Dacal
"['contemporary country', 'country', 'country road', 'modern country rock']",Jaron And The Long Road To Love
['show tunes'],Jasmine Cephas-Jones
['show tunes'],Jason Michael Snow
['show tunes'],Jason Raize
['hollywood'],Jason Segel
['movie tunes'],Jason Weaver
['orchestral performance'],Jean-François Paillard
['orchestral performance'],Jeffrey Tate
"['disney', 'movie tunes']",Jenifer Lewis
"['broadway', 'hollywood', 'show tunes']",Jennifer Damiano
['classical soprano'],Jennifer Vyvyan
['movie tunes'],Jeremy Irons
"['broadway', 'hollywood', 'show tunes']",Jeremy Jordan
['movie tunes'],Jerry Colonna
['movie tunes'],Jesse Corti
"['broadway', 'hollywood', 'show tunes']",Jessica Keenan Wynn
"['broadway', 'hollywood', 'show tunes']",Jessie Mueller
"['broadway', 'hollywood', 'show tunes']",Jewell
['hollywood'],Jim Broadbent
['hollywood'],Jim Bryant
['movie tunes'],Jim Carmichael
['hollywood'],Jim Sturgess
['orchestral performance'],Jiří Bělohlávek
['orchestral performance'],Joann Falletta
['hollywood'],Joaquin Phoenix
['hollywood'],Joe Anderson
"['broadway', 'hollywood', 'show tunes']",John Gallagher Jr.
"['broadway', 'hollywood', 'show tunes']","John Gallagher, Jr."
['hollywood'],John Kander
['gospel'],John P Kee & New Life
['gospel'],John P. Kee
['hollywood'],John Travolta
['hollywood'],Johnny Depp
['hollywood'],Johnny Green
['show tunes'],Jon Eidson
"['contemporary country', 'country', 'country road', 'modern country rock']",Jon Pardi
"['disney', 'movie tunes']",Jonathan Freeman
['gospel'],Jonathan Nelson
['orchestral performance'],Josef K
['orchestral performance'],Josef Krips
"['disney', 'movie tunes']",Joseph Williams
"['contemporary country', 'country', 'country road', 'modern country rock']",Josh Turner
['orchestral performance'],José Serebrier
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",Jowell
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",Jowell & Randy
['hollywood'],Julie Walters
['show tunes'],Justin Bohon
['movie tunes'],Kamehameha Schools Children's Chorus
"['broadway', 'hollywood', 'show tunes']",Kara Lindsay
"['disney', 'movie tunes']",Karen Dotrice
['classical soprano'],Karita Mattila
"['disney', 'movie tunes']",Kathryn Beaumont
"['broadway', 'hollywood', 'show tunes']",Keala Settle
"['broadway', 'hollywood', 'show tunes']",Keenan Wynn
['movie tunes'],Keith David
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",Ken-Y
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",Kendo
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",Kendo Kaponi
['orchestral performance'],Kent Nagano
['show tunes'],Kevin Duda
"['broadway', 'hollywood', 'show tunes']",Kimiko Glenn
"['contemporary country', 'country', 'country road', 'modern country rock']",Kip Moore
['orchestral performance'],Klaus Tennstedt
['gospel'],Kurt Carr & The Kurt Carr Singers
['show tunes'],Kym Karath
['movie tunes'],LaChanze
['gospel'],LaShun Pace
"['broadway', 'hollywood', 'show tunes']",Laura Dreyfuss
['movie tunes'],Laura Williams
"['disney', 'movie tunes']",Lebo M.
"['contemporary country', 'country', 'country road', 'modern country rock']",Lee Brice
['movie tunes'],Leigh Harline
"['broadway', 'hollywood', 'show tunes']",Len Cariou
"['broadway', 'hollywood', 'show tunes']",Leo Norbert Butz
['orchestral performance'],Leonard Slatkin
['orchestral performance'],Leopold Stokowski
['show tunes'],Les Misérables-Original London Cast
"['broadway', 'hollywood', 'show tunes']",Leslie Kritzer
['hollywood'],Levi Stubbs
['show tunes'],Lewis Cleale
['hollywood'],Lily James
['show tunes'],Lin-Manuel Miranda
['show tunes'],Linda Eder
['movie tunes'],Linda Hunt
['classical soprano'],Lisa Otto
['classical soprano'],Lisa della Casa
['movie tunes'],Liz English
['classical soprano'],Ljuba Welitsch
['sleep'],Loopable
['orchestral performance'],Louis Langrée
['sleep'],Lullabies for Deep Meditation
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",Luny Tunes
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",MAGIC!
['movie tunes'],Mack David
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",Magic
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",Magnate Y Valentino
['gospel'],Mali Music
"['broadway', 'hollywood', 'show tunes']",Mandy Gonzalez
['classical soprano'],Margaret Marshall
['orchestral performance'],Mark Elder
['movie tunes'],Mark Keali'i Ho'omalu
['gospel'],Martha Munizzi
['classical soprano'],Martha Mödl
['hollywood'],Martin Luther
['hollywood'],Martin Luther McCoy
['gospel'],Marvin Sapp
"['disney', 'movie tunes']",Mary Costa
"['disney', 'movie tunes']",Mary Moder
"['broadway', 'hollywood', 'show tunes']",Matthew Morrison
['orchestral performance'],Maurice Abravanel
['show tunes'],Max Casella
['sleep'],Meditation Awareness
['movie tunes'],Mel Gibson
['gospel'],Men Of Standard
['hollywood'],Meryl Streep
"['disney', 'movie tunes']",Mice Chorus
['orchestral performance'],Michel Plasson
['show tunes'],Michelle Duffy
['show tunes'],Michelle Federer
['hollywood'],Michelle Pfeiffer
['hollywood'],Michelle Williams
['movie tunes'],Mike Douglas
['show tunes'],Mike Faist
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",Miky Woodz
['show tunes'],Miranda!
['classical soprano'],Monika Frimmer
['show tunes'],Mya Harrison
['movie tunes'],Nancy Adams
['hollywood'],Natalie Mendoza
['sleep'],Native American Flute
['sleep'],Native American Meditations
['sleep'],Natural White Noise Relaxation
['movie tunes'],Ned Washington
['sleep'],New Age
['show tunes'],Nicholas Hammond
['show tunes'],Nick Spangler
['show tunes'],Nicolas Colicos
"['broadway', 'hollywood', 'show tunes']",Norbert Leo Butz
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",Nori
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",Noriel
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",Nova y Jory
['show tunes'],Okieriete Onaodowan
['show tunes'],Olivia Foa'i
['movie tunes'],Oscar Isaac
['orchestral performance'],Osmo Vänskä
['orchestral performance'],Otmar Suitner
['movie tunes'],Paige O'Hara
"['disney', 'movie tunes']",Pat Carroll
"['broadway', 'hollywood', 'show tunes']",Patti LuPone
['hollywood'],Paul Francis Webster
['movie tunes'],Paul Frees
"['disney', 'movie tunes']",Paul Kandel
['movie tunes'],Pearl Bailey
['orchestral performance'],Peter Maag
['movie tunes'],Phil Harris
"['contemporary country', 'country', 'country road', 'modern country rock']",Phil Vassar
['hollywood'],Pierce Brosnan
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",R.K.M & Ken-Y
"['broadway', 'hollywood', 'show tunes']",Rachel Bay Jones
['show tunes'],Rachel House
['movie tunes'],Rachel McDowall
['orchestral performance'],Rafael Kubelik
['sleep'],Rain Storm Sample Library
['hollywood'],Ralph Fiennes
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",Randy
['orchestral performance'],Raymond Leppard
['hollywood'],Reese Witherspoon
['sleep'],Relajación
['sleep'],Relaxation
['classical soprano'],Reri Grist
['hollywood'],Richard Gere
['hollywood'],Richard O'Brien
['gospel'],Richard Smallwood
['movie tunes'],Richard White
['hollywood'],Rick Moranis
"['disney', 'movie tunes']",Robby Benson
['show tunes'],Robert Billig
['orchestral performance'],Robert Shaw
['classical soprano'],Roberta Peters
['show tunes'],Robin de Jesus
"['contemporary country', 'country', 'country road', 'modern country rock']",Rodney Atkins
"['disney', 'movie tunes']",Roger Bart
['show tunes'],Rory O'Malley
"['contemporary country', 'country', 'country road', 'modern country rock']",Russell Dickerson
['classical soprano'],Ruth Ziesak
"['latin', 'latin hip hop', 'reggaeton', 'reggaeton flow', 'trap latino', 'tropical']",Rvssian
['hollywood'],Ryan Gosling
"['broadway', 'hollywood', 'show tunes']",Ryan McCartan
['classical soprano'],Régine Crespin
"['broadway', 'hollywood', 'show tunes']",Saigon
['orchestral performance'],Sakari Oramo
['movie tunes'],Sally Dworsky
['show tunes'],Samantha Barks
['sleep'],Sample Rain Library
['movie tunes'],"Sandy Duncan, Howard McGillin, Liz Callaway, Dakin Matthews, Adam Wylie, J.D. Daniels, Lex de Azevedo, David Zippel"
['hollywood'],Sara Ramirez
['movie tunes'],Scatman Crothers
['show tunes'],Scott Irby-Ranniar
"['contemporary country', 'country', 'country road', 'modern country rock']",Scotty
"['contemporary country', 'country', 'country road', 'modern country rock']",Scotty McCreery
['orchestral performance'],Semyon Bychkov
['classical soprano'],Sena Jurinac
['show tunes'],Seth Stewart
['movie tunes'],Shelby Flint
"['broadway', 'hollywood', 'show tunes']",Sherie Rene Scott
"['disney', 'movie tunes']",Ship's Chorus
"['disney', 'movie tunes']",Si and Am
['show tunes'],Sierra Boggess as Ariel
['orchestral performance'],Sir Adrian Boult
['orchestral performance'],Sir Charles Groves
['orchestral performance'],Sir Charles Mackerras
['orchestral performance'],Sir David Willcocks
['orchestral performance'],Sir Georg Solti
['orchestral performance'],Sir Thomas Beecham
['sleep'],Sleep Baby Sleep
['sleep'],Sleep Sound Library
['sleep'],Sleepy Times
['sleep'],"Soothing White Noise for Infant Sleeping and Massage, Crying & Colic Relief"